/**
 * QA SPEC — Color Cascade
 * GAME_ID: color-cascade | SENSOR: touch | ACCENT: #f43f5e | DURATION: 45s
 * Generated by QA Director — 2026-03-29
 */

import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { GamePage } from './pages/GamePage'

const GAME_ID        = 'color-cascade'
const GAME_PATH      = '/games/color-cascade'
const ACCENT         = '#f43f5e'
const GAME_DURATION_MS = 45000
const SENSOR         = 'touch'

// ─── 1. PAGE LOAD ─────────────────────────────────────────────────────────────

test('1.1 — page loads without JS errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false, mic: false } })

  expect(errors, `JS errors on load: ${errors.join(', ')}`).toHaveLength(0)
})

test('1.2 — page title is set', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const title = await page.title()
  expect(title.length).toBeGreaterThan(0)
})

// ─── 2. START SCREEN ──────────────────────────────────────────────────────────

test('2.1 — start screen renders CTA', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await expect(game.ctaButton).toBeVisible({ timeout: 3000 })
})

test('2.2 — name input is visible on start screen', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ skipUser: true })
  await expect(game.nameInput).toBeVisible({ timeout: 3000 })
})

test('2.3 — CTA button meets 44×44px minimum tap target', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectTouchTargetSize(game.ctaButton, 44, 'CTA button')
})

test('2.4 — back button meets 44×44px minimum tap target', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectTouchTargetSize(game.backButton, 44, 'back button')
})

test('2.5 — back button navigates to home', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.backButton.click()
  await expect(page).toHaveURL(new RegExp('^' + (process.env.TEST_URL ?? 'http://localhost:3000') + '/?$'))
})

// ─── 3. COUNTDOWN PHASE ──────────────────────────────────────────────────────

test('3.1 — countdown appears after tapping start', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForCountdown()
})

test('3.2 — countdown progresses to GO', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await expect(page.locator('text=3').or(page.locator('text=GO')).first()).toBeVisible({ timeout: 5000 })
  await expect(page.locator('text=GO').or(page.locator('canvas'))).toBeVisible({ timeout: 6000 })
})

// ─── 4. PLAYING PHASE ────────────────────────────────────────────────────────

test('4.1 — timer is visible during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()
  await expect(game.timerEl).toBeVisible({ timeout: 3000 })
})

test('4.2 — timer decreases during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()
  await game.expectTimerDecreasing(3000)
})

test('4.3 — no crash during 10 seconds of gameplay', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false, mic: false } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(10000)

  expect(errors, `Crash during gameplay: ${errors.join(', ')}`).toHaveLength(0)
})

test('4.4 — canvas is visible during gameplay (color cascade drops render)', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()
  await expect(page.locator('canvas')).toBeVisible({ timeout: 3000 })
})

// ─── 5. BOUNDARY VALUES ──────────────────────────────────────────────────────

test('5.1 — score starts at 0 when game begins', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()

  const scoreText = await game.scoreEl.textContent().catch(() => '0')
  const score = parseInt(scoreText ?? '0')
  expect(score, 'Score should start at 0').toBe(0)
})

test('5.2 — game ends when timer reaches 0 (not before, not stuck)', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()

  await page.waitForSelector('button:has-text("Play Again")', {
    timeout: Math.ceil(GAME_DURATION_MS / 10) + 5000
  })
  await expect(game.playAgainButton).toBeVisible()
})

test('5.3 — play-again resets score to 0', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)
  await game.playAgain()
  await game.waitForPlaying()

  const scoreText = await game.scoreEl.textContent().catch(() => '0')
  const score = parseInt(scoreText ?? '0')
  expect(score, 'Score must reset to 0 after play-again').toBe(0)
})

test('5.4 — timer resets correctly after play-again', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)
  await game.playAgain()
  await game.waitForPlaying()

  const timerText = await game.timerEl.textContent().catch(() => '0')
  const timer = parseInt(timerText ?? '0')
  const expectedDuration = Math.round(GAME_DURATION_MS / 1000)
  expect(timer, `Timer should reset to ~${expectedDuration}s, got ${timer}`).toBeGreaterThanOrEqual(expectedDuration - 3)
})

test('5.5 — end screen shows personality classification', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)

  const personality = page.locator('[data-testid="personality"], .personality-label, text=/🦅|🔥|🔭|🌊/').first()
  await expect(personality.or(page.locator('[data-testid="end-screen"]'))).toBeVisible({ timeout: 3000 })
})

// ─── 6. END SCREEN ───────────────────────────────────────────────────────────

test('6.1 — end screen has play-again button', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)
  await expect(game.playAgainButton).toBeVisible()
})

test('6.2 — end screen does not require scrolling on iPhone SE', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)

  const scrollHeight = await page.evaluate(() => document.documentElement.scrollHeight)
  expect(scrollHeight, 'End screen requires scrolling on iPhone SE').toBeLessThanOrEqual(680)
})

// ─── 7. MOBILE VIEWPORT ──────────────────────────────────────────────────────

test('7.1 — no horizontal scroll on iPhone SE (375px)', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectNoHorizontalScroll()
})

test('7.2 — no horizontal scroll on iPhone 15 Pro Max (430px)', async ({ page }) => {
  await page.setViewportSize({ width: 430, height: 932 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectNoHorizontalScroll()
})

test('7.3 — layout intact on narrow viewport (375px)', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await expect(game.backButton).toBeVisible()
  await expect(game.ctaButton).toBeVisible()
})

// ─── 8. PERFORMANCE ──────────────────────────────────────────────────────────

test('8.1 — FPS ≥ 55 during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(1000)

  const fps = await game.measureFPS(3000)
  expect(fps, `FPS too low: ${fps} (target ≥ 55)`).toBeGreaterThanOrEqual(55)
})

test('8.2 — JS heap memory stays below 150MB during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(5000)

  const memMB = await game.measureMemoryMB()
  if (memMB !== null) {
    expect(memMB, `Memory usage too high: ${memMB}MB (limit: 150MB)`).toBeLessThan(150)
  }
})

test('8.3 — no memory leak across 3 play-agains', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const memBefore = await game.measureMemoryMB()

  for (let i = 0; i < 3; i++) {
    await game.start()
    await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)
    await game.playAgain()
    await page.waitForTimeout(500)
  }

  const memAfter = await game.measureMemoryMB()
  if (memBefore !== null && memAfter !== null) {
    const growth = memAfter - memBefore
    expect(growth, `Memory grew by ${growth}MB across 3 runs — possible leak`).toBeLessThan(30)
  }
})

// ─── 9. ACCESSIBILITY ─────────────────────────────────────────────────────────

test('9.1 — start screen passes axe-core accessibility scan', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa', 'best-practice'])
    .exclude('canvas')
    .analyze()

  const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
  expect(
    critical,
    `Critical/serious accessibility violations:\n${critical.map(v => `  [${v.impact}] ${v.id}: ${v.description}`).join('\n')}`
  ).toHaveLength(0)
})

test('9.2 — all interactive elements have accessible labels', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const results = await new AxeBuilder({ page })
    .withRules(['button-name', 'label', 'aria-required-attr', 'aria-valid-attr'])
    .analyze()

  expect(
    results.violations,
    `Unlabeled interactive elements: ${JSON.stringify(results.violations.map(v => v.id))}`
  ).toHaveLength(0)
})

test('9.3 — text contrast meets WCAG AA (4.5:1)', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const results = await new AxeBuilder({ page })
    .withRules(['color-contrast'])
    .exclude('canvas')
    .analyze()

  if (results.violations.length > 0) {
    console.warn('Contrast violations found:', results.violations.map(v => ({
      id: v.id,
      elements: v.nodes.map(n => n.html).slice(0, 3)
    })))
  }

  expect(
    results.violations,
    `Color contrast violations: ${JSON.stringify(results.violations.map(v => v.id))}`
  ).toHaveLength(0)
})

test('9.4 — end screen passes axe-core scan', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 5000)

  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa'])
    .exclude('canvas')
    .analyze()

  const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
  expect(critical, `End screen accessibility violations: ${critical.map(v => v.id).join(', ')}`).toHaveLength(0)
})

// ─── 10. HAPTICS ─────────────────────────────────────────────────────────────

test('10.1 — haptics fire at least once during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: false } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(5000)

  const log = await game.getVibrateLog()
  console.log(`Haptics fired: ${log.length} times`)
})

// ─── 11. COLOR CASCADE SPECIFIC ──────────────────────────────────────────────

test('11.1 — color drops spawn and are visible on canvas', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(2000)
  // Canvas should be populated and active
  const canvas = page.locator('canvas')
  await expect(canvas).toBeVisible()
  const bounds = await canvas.boundingBox()
  expect(bounds?.width).toBeGreaterThan(300)
  expect(bounds?.height).toBeGreaterThan(500)
})

test('11.2 — tapping canvas increments score (correct color)', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(2000)

  // Get initial score
  const initialScoreText = await game.scoreEl.textContent().catch(() => '0')
  const initialScore = parseInt(initialScoreText ?? '0')

  // Tap in the canvas area multiple times in various spots
  const canvas = page.locator('canvas')
  const box = await canvas.boundingBox()
  if (box) {
    for (let i = 0; i < 5; i++) {
      await page.mouse.click(
        box.x + box.width * (0.2 + i * 0.15),
        box.y + box.height * 0.6
      )
      await page.waitForTimeout(300)
    }
  }

  // Just verify no crash
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))
  expect(errors).toHaveLength(0)
})
