/**
 * Stack Drop — QA Test Suite
 * Generated by QA Agent | 2026-03-29
 */

import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { GamePage } from './pages/GamePage'

const GAME_ID         = 'stack-drop'
const GAME_PATH       = '/games/stack-drop'
const ACCENT          = '#f97316'
const GAME_DURATION_MS = 45000   // actual coded duration (45s)
const SENSOR          = 'touch'

// Helper to skip SwipeInstructions on first load
const skipInstructions = async (context: import('@playwright/test').BrowserContext) => {
  await context.addInitScript(() => {
    localStorage.setItem('seen_stack-drop', '1');
  });
};

// ─── 1. PAGE LOAD ─────────────────────────────────────────────────────────────

test('1.1 — page loads without JS errors', async ({ page, context }) => {
  await skipInstructions(context);
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  expect(errors, `JS errors on load: ${errors.join(', ')}`).toHaveLength(0)
})

test('1.2 — page title is set', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const title = await page.title()
  expect(title.length).toBeGreaterThan(0)
})

// ─── 2. START SCREEN ──────────────────────────────────────────────────────────

test('2.1 — start screen renders with CTA button', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await expect(game.ctaButton).toBeVisible({ timeout: 3000 })
})

test('2.2 — name input is visible on start screen', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ skipUser: true })
  await expect(game.nameInput).toBeVisible({ timeout: 3000 })
})

test('2.3 — CTA button meets 44×44px minimum tap target', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectTouchTargetSize(game.ctaButton, 44, 'CTA button')
})

test('2.4 — back button meets 44×44px minimum tap target', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectTouchTargetSize(game.backButton, 44, 'back button')
})

// ─── 3. COUNTDOWN PHASE ──────────────────────────────────────────────────────

test('3.1 — countdown appears after tapping start', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForCountdown()
})

test('3.2 — countdown progresses to GO then playing', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await expect(page.locator('[data-testid="countdown-display"]')).toBeVisible({ timeout: 5000 })
  await page.waitForTimeout(3500)
  await expect(game.timerEl).toBeVisible({ timeout: 3000 })
})

// ─── 4. PLAYING PHASE ────────────────────────────────────────────────────────

test('4.1 — timer is visible during gameplay', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await expect(game.timerEl).toBeVisible({ timeout: 3000 })
})

test('4.2 — timer decreases during gameplay', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await game.expectTimerDecreasing(3000)
})

test('4.3 — no crash during 10 seconds of gameplay', async ({ page, context }) => {
  await skipInstructions(context);
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(10000)
  expect(errors, `Crash during gameplay: ${errors.join(', ')}`).toHaveLength(0)
})

// ─── 5. BOUNDARY VALUES ──────────────────────────────────────────────────────

test('5.1 — score/height starts at 0 when game begins', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  const scoreText = await game.scoreEl.textContent().catch(() => '0')
  const score = parseInt(scoreText ?? '0')
  expect(score, 'Score should start at 0').toBe(0)
})

test('5.2 — game ends when timer reaches 0', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await page.waitForSelector('button:has-text("Play Again")', {
    timeout: Math.ceil(GAME_DURATION_MS / 10) + 6000
  })
  await expect(game.playAgainButton).toBeVisible()
})

test('5.3 — play-again resets score to 0', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
  await game.playAgain()
  await game.waitForPlaying()
  const scoreText = await game.scoreEl.textContent().catch(() => '0')
  expect(parseInt(scoreText ?? '0')).toBe(0)
})

test('5.4 — timer resets after play-again', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
  await game.playAgain()
  await game.waitForPlaying()
  const timerText = await game.timerEl.textContent().catch(() => '0')
  const timer = parseInt(timerText ?? '0')
  expect(timer).toBeGreaterThanOrEqual(40)
})

test('5.5 — end screen shows personality classification', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
  const personality = page.locator('[data-testid="personality"], .personality-label').first()
  const anyText = page.locator('text=/Trailblazer|Optimizer|Energizer|Explorer|Connector/').first()
  await expect(personality.or(anyText)).toBeVisible({ timeout: 5000 })
})

// ─── 6. END SCREEN ───────────────────────────────────────────────────────────

test('6.1 — end screen has play-again button', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
  await expect(game.playAgainButton).toBeVisible()
})

test('6.2 — end screen does not require scrolling on iPhone SE', async ({ page, context }) => {
  await skipInstructions(context);
  await page.setViewportSize({ width: 375, height: 667 })
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
  const scrollHeight = await page.evaluate(() => document.documentElement.scrollHeight)
  expect(scrollHeight).toBeLessThanOrEqual(680)
})

// ─── 7. MOBILE VIEWPORT ──────────────────────────────────────────────────────

test('7.1 — no horizontal scroll on iPhone SE (375px)', async ({ page, context }) => {
  await skipInstructions(context);
  await page.setViewportSize({ width: 375, height: 667 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectNoHorizontalScroll()
})

test('7.2 — no horizontal scroll on iPhone 15 Pro Max (430px)', async ({ page, context }) => {
  await skipInstructions(context);
  await page.setViewportSize({ width: 430, height: 932 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectNoHorizontalScroll()
})

// ─── 8. PERFORMANCE ──────────────────────────────────────────────────────────

test('8.1 — FPS ≥ 55 during gameplay', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(1000)
  const fps = await game.measureFPS(3000)
  expect(fps, `FPS too low: ${fps} (target ≥ 55)`).toBeGreaterThanOrEqual(55)
})

test('8.2 — JS heap < 150MB during gameplay', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(5000)
  const memMB = await game.measureMemoryMB()
  if (memMB !== null) {
    expect(memMB).toBeLessThan(150)
  }
})

test('8.3 — no memory leak across 3 play-agains', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const memBefore = await game.measureMemoryMB()
  for (let i = 0; i < 3; i++) {
    await game.start()
    await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
    await game.playAgain()
    await page.waitForTimeout(500)
  }
  const memAfter = await game.measureMemoryMB()
  if (memBefore !== null && memAfter !== null) {
    const growth = memAfter - memBefore
    expect(growth, `Memory grew ${growth}MB across 3 runs`).toBeLessThan(30)
  }
})

// ─── 9. ACCESSIBILITY (axe-core) ─────────────────────────────────────────────

test('9.1 — start screen passes axe-core scan', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa', 'best-practice'])
    .exclude('canvas')
    .analyze()
  const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
  expect(critical, `Critical violations:\n${critical.map(v => `  [${v.impact}] ${v.id}: ${v.description}`).join('\n')}`).toHaveLength(0)
})

test('9.2 — all interactive elements have accessible labels', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const results = await new AxeBuilder({ page })
    .withRules(['button-name', 'label', 'aria-required-attr'])
    .analyze()
  expect(results.violations, `Unlabeled elements: ${JSON.stringify(results.violations.map(v => v.id))}`).toHaveLength(0)
})

test('9.3 — text contrast meets WCAG AA', async ({ page, context }) => {
  await skipInstructions(context);
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const results = await new AxeBuilder({ page })
    .withRules(['color-contrast'])
    .exclude('canvas')
    .analyze()
  if (results.violations.length > 0) {
    console.warn('Contrast issues:', results.violations.map(v => v.nodes.map(n => n.html)))
  }
  expect(results.violations).toHaveLength(0)
})

test('9.4 — end screen passes axe-core scan', async ({ page, context }) => {
  await skipInstructions(context);
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 6000)
  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa'])
    .exclude('canvas')
    .analyze()
  const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
  expect(critical, `End screen violations: ${critical.map(v => v.id).join(', ')}`).toHaveLength(0)
})
