/**
 * Steady Hand — QA Playwright Spec
 * Generated by QA Agent | 2026-03-18
 *
 * Sensor: DeviceMotion (accelerometer) | Duration: 30s | Accent: #22c55e
 * Run: npx playwright test tests/steady-hand.spec.ts --reporter=line
 */

import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { GamePage } from './pages/GamePage'

// ─── CONFIG ──────────────────────────────────────────────────────────────────
const GAME_ID         = 'steady-hand'
const GAME_PATH       = '/games/steady-hand'
const ACCENT          = '#22c55e'
const GAME_DURATION_MS = 30000
const SENSOR          = 'motion'
// ─────────────────────────────────────────────────────────────────────────────

// ─── 1. PAGE LOAD ─────────────────────────────────────────────────────────────

test('1.1 — page loads without JS errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()) })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })

  expect(errors, `JS errors on load: ${errors.join(', ')}`).toHaveLength(0)
})

test('1.2 — page title is set', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const title = await page.title()
  expect(title.length).toBeGreaterThan(0)
})

// ─── 2. START SCREEN ──────────────────────────────────────────────────────────

test('2.1 — start screen renders with CTA', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await expect(game.ctaButton).toBeVisible({ timeout: 3000 })
})

test('2.2 — name input is visible on start screen', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ skipUser: true })
  await expect(game.ctaButton).toBeVisible({ timeout: 3000 })
  // CTA tap triggers PlayerNameInput overlay
  await game.ctaButton.click()
  await expect(game.nameInput).toBeVisible({ timeout: 3000 })
})

test('2.3 — CTA button meets 44×44px minimum tap target', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectTouchTargetSize(game.ctaButton, 44, 'CTA button')
})

test('2.4 — back button meets 44×44px minimum tap target', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectTouchTargetSize(game.backButton, 44, 'back button')
})

test('2.5 — back button navigates to home', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.backButton.click()
  await expect(page).toHaveURL(new RegExp('^' + (process.env.TEST_URL ?? 'http://localhost:3000') + '/?$'))
})

test('2.6 — theme toggle button is visible (44×44px)', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  const themeToggle = page.locator('button[aria-label*="light mode"], button[aria-label*="dark mode"]').first()
  await expect(themeToggle).toBeVisible({ timeout: 3000 })
  const box = await themeToggle.boundingBox()
  expect(box?.width ?? 0, 'Theme toggle width').toBeGreaterThanOrEqual(44)
  expect(box?.height ?? 0, 'Theme toggle height').toBeGreaterThanOrEqual(44)
})

// ─── 3. COUNTDOWN PHASE ──────────────────────────────────────────────────────

test('3.1 — countdown appears after tapping start', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForCountdown()
})

test('3.2 — countdown progresses to GO then playing', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await expect(page.locator('text=3').or(page.locator('text=GO')).first()).toBeVisible({ timeout: 5000 })
  await expect(page.locator('canvas')).toBeVisible({ timeout: 6000 })
})

// ─── 4. PLAYING PHASE ────────────────────────────────────────────────────────

test('4.1 — timer (TIME) is visible during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await expect(game.timerEl).toBeVisible({ timeout: 3000 })
})

test('4.2 — timer decreases during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await game.expectTimerDecreasing(3000)
})

test('4.3 — canvas is rendered during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await expect(game.canvas).toBeVisible({ timeout: 3000 })
})

test('4.4 — no crash during 10 seconds of gameplay', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', err => errors.push(err.message))

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(10000)

  expect(errors, `Crash during gameplay: ${errors.join(', ')}`).toHaveLength(0)
})

// ─── 5. BOUNDARY VALUES ──────────────────────────────────────────────────────

test('5.1 — score (ON TARGET) starts at 0%', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()

  const scoreText = await game.scoreEl.textContent().catch(() => '0%')
  // Score starts at 0% or 0
  expect(scoreText?.replace('%', '').trim()).toBe('0')
})

test('5.2 — game ends when timer reaches 0', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)  // 10x faster
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()

  await page.waitForSelector('button:has-text("Play Again")', {
    timeout: Math.ceil(GAME_DURATION_MS / 10) + 8000
  })
  await expect(game.playAgainButton).toBeVisible()
})

test('5.3 — play-again resets score to 0', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)
  await game.playAgain()
  await game.waitForPlaying()

  const scoreText = await game.scoreEl.textContent().catch(() => '0%')
  expect(scoreText?.replace('%', '').trim()).toBe('0')
})

test('5.4 — timer resets correctly after play-again', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)
  await game.playAgain()
  await game.waitForPlaying()

  const timerText = await game.timerEl.textContent().catch(() => '0')
  const timer = parseInt(timerText ?? '0')
  expect(timer).toBeGreaterThanOrEqual(27)  // at least 27 of 30 (accounting for startup delay)
})

test('5.5 — end screen shows personality classification', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)

  // Personality label must be visible with expected personality names
  const personalities = [
    'Surgeon', 'Steady as a Rock', 'Iron Nerve', 'Focused', 'Getting There', 'Shaky But Brave'
  ]
  let found = false
  for (const p of personalities) {
    try {
      const el = page.locator(`text=${p}`).first()
      if (await el.isVisible({ timeout: 1000 })) { found = true; break }
    } catch { /* continue */ }
  }
  expect(found, 'Personality classification not visible on end screen').toBe(true)
})

// ─── 6. END SCREEN ───────────────────────────────────────────────────────────

test('6.1 — end screen has play-again button', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)
  await expect(game.playAgainButton).toBeVisible()
})

test('6.2 — end screen has 4 insight chips', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)

  // Check for the 4 insight labels
  await expect(page.locator('text=Time on Target').first()).toBeVisible({ timeout: 3000 })
  await expect(page.locator('text=Avg Deviation').first()).toBeVisible({ timeout: 3000 })
  await expect(page.locator('text=Max Streak').first()).toBeVisible({ timeout: 3000 })
  await expect(page.locator('text=Interference Survived').first()).toBeVisible({ timeout: 3000 })
})

test('6.3 — end screen does not require scrolling on iPhone SE (667px)', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)

  // Play Again button must be in view (sticky at bottom)
  await expect(game.playAgainButton).toBeInViewport({ timeout: 3000 })
})

// ─── 7. MOBILE VIEWPORT ──────────────────────────────────────────────────────

test('7.1 — no horizontal scroll on iPhone SE (375px)', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectNoHorizontalScroll()
})

test('7.2 — no horizontal scroll on iPhone 15 Pro Max (430px)', async ({ page }) => {
  await page.setViewportSize({ width: 430, height: 932 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.expectNoHorizontalScroll()
})

test('7.3 — layout intact on narrow viewport (375px)', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await expect(game.backButton).toBeVisible()
  await expect(game.ctaButton).toBeVisible()
})

// ─── 8. PERFORMANCE ──────────────────────────────────────────────────────────

test('8.1 — FPS ≥ 55 during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(1000)

  const fps = await game.measureFPS(3000)
  expect(fps, `FPS too low: ${fps} (target ≥ 55)`).toBeGreaterThanOrEqual(55)
})

test('8.2 — JS heap stays below 150MB during gameplay', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(5000)

  const memMB = await game.measureMemoryMB()
  if (memMB !== null) {
    expect(memMB, `Memory too high: ${memMB}MB`).toBeLessThan(150)
  }
})

test('8.3 — no memory leak across 3 play-agains', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const memBefore = await game.measureMemoryMB()

  for (let i = 0; i < 3; i++) {
    await game.start()
    await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)
    await game.playAgain()
    await page.waitForTimeout(500)
  }

  const memAfter = await game.measureMemoryMB()
  if (memBefore !== null && memAfter !== null) {
    const growth = memAfter - memBefore
    expect(growth, `Memory grew ${growth}MB across 3 runs`).toBeLessThan(30)
  }
})

// ─── 9. ACCESSIBILITY ────────────────────────────────────────────────────────

test('9.1 — start screen passes axe-core scan', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa', 'best-practice'])
    .exclude('canvas')
    .analyze()

  const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
  expect(
    critical,
    `Accessibility violations: ${critical.map(v => `[${v.impact}] ${v.id}`).join(', ')}`
  ).toHaveLength(0)
})

test('9.2 — all interactive elements have accessible labels', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const results = await new AxeBuilder({ page })
    .withRules(['button-name', 'label', 'aria-required-attr'])
    .analyze()

  expect(
    results.violations,
    `Unlabeled elements: ${results.violations.map(v => v.id).join(', ')}`
  ).toHaveLength(0)
})

test('9.3 — text contrast meets WCAG AA', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()

  const results = await new AxeBuilder({ page })
    .withRules(['color-contrast'])
    .exclude('canvas')
    .analyze()

  if (results.violations.length > 0) {
    console.warn('Contrast violations:', results.violations.map(v => v.id))
  }
  expect(results.violations).toHaveLength(0)
})

test('9.4 — end screen passes axe-core scan', async ({ page }) => {
  await page.addInitScript(() => {
    const orig = window.setInterval.bind(window)
    ;(window as any).setInterval = (fn: () => void, ms: number, ...args: unknown[]) => {
      if (ms === 1000) return orig(fn, 100, ...args)
      return orig(fn, ms, ...args)
    }
  })

  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForEnd(GAME_DURATION_MS / 10 + 8000)

  const results = await new AxeBuilder({ page })
    .withTags(['wcag2a', 'wcag2aa'])
    .exclude('canvas')
    .analyze()

  const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
  expect(critical, `End screen violations: ${critical.map(v => v.id).join(', ')}`).toHaveLength(0)
})

// ─── 10. MOTION GAME SPECIFIC ─────────────────────────────────────────────────

test('10.1 — touch fallback activates when motion denied', async ({ page }) => {
  await page.addInitScript(() => {
    ;(window as any).DeviceMotionEvent = class extends Event {
      static requestPermission = async () => 'denied'
      accelerationIncludingGravity = { x: 0, y: 0, z: 9.8 }
    }
  })
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto()
  await game.start()
  await game.waitForPlaying()
  // Game should still render canvas (touch fallback active)
  await expect(game.canvas).toBeVisible({ timeout: 3000 })
})

test('10.2 — haptics=off URL param disables vibration', async ({ page }) => {
  // Inject vibrate spy before load
  await page.addInitScript(() => {
    ;(window as any).__vibrateLog = []
    navigator.vibrate = (pattern: number | number[]) => {
      ;(window as any).__vibrateLog.push(pattern)
      return true
    }
  })

  // Navigate WITH haptics=off
  const game = new GamePage(page, GAME_PATH + '?haptics=off', ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(3000)

  // No vibration should have fired during the game
  const log = await page.evaluate(() => (window as any).__vibrateLog)
  expect(log.length, 'Vibrations fired despite haptics=off').toBe(0)
})

// ─── 11. HAPTICS LOG ─────────────────────────────────────────────────────────

test('11.1 — haptics fire during gameplay (default)', async ({ page }) => {
  const game = new GamePage(page, GAME_PATH, ACCENT)
  await game.goto({ sensors: { motion: true } })
  await game.start()
  await game.waitForPlaying()
  await page.waitForTimeout(5000)

  const log = await game.getVibrateLog()
  console.log(`Haptics fired: ${log.length} times in 5s`)
  // Interference starts at ~6s, so in 5s we may not have one. Don't fail.
})
