// Auto-generated by scripts/gen-instructions.js
// Do not edit manually — regenerate with: node scripts/gen-instructions.js

export const GAME_INSTRUCTIONS: Record<string, { howToPlay: string; controls: string; goal: string }> = {
  'paint-splash': {
    howToPlay: "Shake and tilt your device to splatter paint on the canvas and cover it completely before time runs out.",
    controls: "Shake and tilt your device to control the paint splatter.",
    goal: "Cover the canvas with paint before the time runs out.",
  },
  'web-weave': {
    howToPlay: "Drag your finger between the anchors to weave a web and catch as many flies as possible before the time runs out.",
    controls: "Drag between anchors to weave the web.",
    goal: "Catch as many flies as you can by weaving the web.",
  },
  'treasure-dive': {
    howToPlay: "Tilt your device to steer your diver and collect as much treasure as possible while avoiding the sharks.",
    controls: "Tilt your device to control the diver's movement.",
    goal: "Collect as much treasure as you can while avoiding the sharks.",
  },
  'frog-leap': {
    howToPlay: "Tap the left or right side of the screen to make the frog leap from one lily pad to the next. Don't let the frog fall in the water.",
    controls: "Tap left or right to make the frog leap.",
    goal: "Leap from lily pad to lily pad without falling in the water.",
  },
  'wire-cross': {
    howToPlay: "Guide the ring through the wire maze without touching the wire. If you touch the wire, you lose.",
    controls: "Drag the ring to navigate the wire maze.",
    goal: "Guide the ring through the wire maze without touching the wire.",
  },
  'balloon-pop': {
    howToPlay: "Pinch the screen to pop the balloons before they overflow the screen.",
    controls: "Pinch the screen to pop the balloons.",
    goal: "Pop all the balloons before they overflow the screen.",
  },
  'slingshot-smash': {
    howToPlay: "Stretch the slingshot, aim, and release to smash the targets.",
    controls: "Stretch the slingshot, aim, and release to shoot.",
    goal: "Smash all the targets before the time runs out.",
  },
  'ripple-tap': {
    howToPlay: "Tap the screen at the peak of the ripple. Timing is key to score points.",
    controls: "Tap the screen at the peak of the ripple.",
    goal: "Tap the screen at the peak of the ripple to score as many points as possible.",
  },
  'pendulum-swing': {
    howToPlay: "Tap the screen to keep the pendulum swinging in rhythm. Don't let it stop.",
    controls: "Tap the screen to keep the pendulum swinging.",
    goal: "Keep the pendulum swinging in rhythm for as long as possible.",
  },
  'node-connect': {
    howToPlay: "Connect the nodes by drawing lines between them without crossing any existing lines.",
    controls: "Drag to connect the nodes.",
    goal: "Connect all the nodes without crossing any existing lines.",
  },
  'orbit-launch': {
    howToPlay: "Aim and launch the satellite to enter a stable orbit around the planet.",
    controls: "Aim and launch the satellite.",
    goal: "Achieve a stable orbit around the planet.",
  },
  'speed-sort': {
    howToPlay: "Quickly tap the left or right side of the screen to sort the falling objects into the correct bins.",
    controls: "Tap left or right to sort the falling objects.",
    goal: "Sort as many falling objects as possible before time runs out.",
  },
  'spring-leap': {
    howToPlay: "Hold and release the screen to charge and launch the spring-powered character. Time your release to make the perfect leap.",
    controls: "Hold and release the screen to charge and launch the spring.",
    goal: "Time your leap to reach the target platform.",
  },
  'crystal-catch': {
    howToPlay: "Tilt your device to guide the crystal catcher and collect as many crystals as possible without letting them shatter.",
    controls: "Tilt your device to control the crystal catcher.",
    goal: "Collect as many crystals as you can without letting them shatter.",
  },
  'wobble-stack': {
    howToPlay: "Tap the screen to stack blocks, but be careful as the stack becomes more unstable over time.",
    controls: "Tap the screen to stack the blocks.",
    goal: "Stack the blocks as high as possible before the tower topples over.",
  },
  'chain-reaction': {
    howToPlay: "Tap a single block to trigger a chain reaction of explosions. See how much chaos you can create.",
    controls: "Tap a single block to start the chain reaction.",
    goal: "Trigger the maximum chain reaction from a single tap.",
  },
  'pixel-paint': {
    howToPlay: "Quickly tap the screen to speed-paint the revealed pattern before time runs out.",
    controls: "Tap the screen to paint the pattern.",
    goal: "Complete the painting pattern before the time runs out.",
  },
  'drop-zone': {
    howToPlay: "Time your release to drop the falling object into the target zone.",
    controls: "Release the falling object at the right moment.",
    goal: "Drop the object into the target zone.",
  },
  'laser-guide': {
    howToPlay: "Reflect the laser beam by tilting your device to hit the target.",
    controls: "Tilt your device to reflect the laser beam.",
    goal: "Reflect the laser beam to hit the target.",
  },
  'friction-slide': {
    howToPlay: "Flick the object with precision to slide it and stop it on the target.",
    controls: "Flick the object to slide it and stop it on the target.",
    goal: "Slide the object and stop it on the target.",
  },
  'gravity-well': {
    howToPlay: "Tap and hold the screen to orbit the gravity well. Avoid getting pulled in by the strong gravitational forces.",
    controls: "Tap and hold the screen to orbit the well.",
    goal: "Survive as long as possible without getting pulled into the well.",
  },
  'tilt-maze': {
    howToPlay: "Tilt your device to roll the ball through the maze. Navigate around obstacles and reach the goal.",
    controls: "Tilt your device to roll the ball.",
    goal: "Guide the ball to the end of the maze.",
  },
  'whisper-bomb': {
    howToPlay: "Stay perfectly silent to defuse the bomb. Make any sound, and it will explode.",
    controls: "Remain silent and hold your breath.",
    goal: "Defuse the bomb without making a sound.",
  },
  'breath-rider': {
    howToPlay: "Control the rider's flight by inhaling and exhaling. Navigate through the obstacles and reach the finish line.",
    controls: "Inhale and exhale to control the rider's flight.",
    goal: "Reach the finish line by flying through the obstacles.",
  },
  'steady-hand': {
    howToPlay: "Hold your device perfectly still. The slightest movement will cause the game to end.",
    controls: "Hold your device as still as possible.",
    goal: "Hold your device steady for the entire duration.",
  },
  'tunnel': {
    howToPlay: "Dodge the rings as you travel through the infinite tunnel. Swipe left or right to avoid crashing.",
    controls: "Swipe left and right to dodge the rings.",
    goal: "Survive as long as possible without crashing.",
  },
  'pulse-sphere': {
    howToPlay: "Interact with the pulse sphere by tapping, moving, and controlling your breath. Observe how the sphere responds to your actions.",
    controls: "Tap, move, and control your breath to interact with the sphere.",
    goal: "Explore the sphere's responsive behavior.",
  },
  'shadow-tap': {
    howToPlay: "Tap the shadows as they appear on the screen. Be quick, as they disappear rapidly.",
    controls: "Tap the shadows before they disappear.",
    goal: "Tap as many shadows as possible before time runs out.",
  },
  'color-cascade': {
    howToPlay: "Match the color and speed of the falling blocks by tapping them. React quickly as the speed increases.",
    controls: "Tap the falling blocks to match their color and speed.",
    goal: "Score as many points as possible by matching the blocks.",
  },
  'equation-tap': {
    howToPlay: "Solve the mathematical equations by tapping the correct answer before time runs out.",
    controls: "Tap the correct answer to the equations.",
    goal: "Solve as many equations as possible within the time limit.",
  },
  'color-word': {
    howToPlay: "Ignore the written word and tap the color of the text instead. Avoid the trap of reading the word.",
    controls: "Tap the color of the text, not the written word.",
    goal: "Tap as many colors as possible before time expires.",
  },
  'visual-search': {
    howToPlay: "Find and tap the hidden target before the horde of distractors takes over the screen.",
    controls: "Tap the hidden target as quickly as possible.",
    goal: "Locate and tap the target before time runs out.",
  },
  'odd-one-out': {
    howToPlay: "Quickly identify the item that doesn't belong in the group and tap it.",
    controls: "Tap the item that doesn't belong in the group.",
    goal: "Find and tap the odd one out as many times as possible.",
  },
  'pattern-predict': {
    howToPlay: "Observe the pattern and predict what comes next. Tap the correct answer to score points.",
    controls: "Tap the answer that completes the pattern.",
    goal: "Correctly predict the next item in the pattern.",
  },
  'reflex-grid': {
    howToPlay: "Quickly tap the flashing square on the grid. Avoid missing any flashes.",
    controls: "Tap the flashing square on the grid.",
    goal: "Tap the flashing squares without missing any.",
  },
  'sequence-unlock': {
    howToPlay: "Memorize the sequence of flashing lights and repeat it correctly to unlock the code.",
    controls: "Repeat the sequence of flashing lights.",
    goal: "Correctly recall and repeat the sequence of flashes.",
  },
  'word-flash': {
    howToPlay: "Read the word that appears on the screen, remember it, and recall it when prompted.",
    controls: "Read and remember the words that appear.",
    goal: "Correctly recall the words that were shown.",
  },
  'rhythm-repeat': {
    howToPlay: "Listen to the rhythm and tap the screen to reproduce the pattern.",
    controls: "Tap the screen to repeat the rhythm.",
    goal: "Accurately repeat the rhythm you hear.",
  },
  'category-clash': {
    howToPlay: "Sort the items that appear on the screen into their respective categories as quickly as possible.",
    controls: "Tap the items to sort them into the correct categories.",
    goal: "Sort as many items as you can before time runs out.",
  },
  'memory-grid': {
    howToPlay: "Remember the pattern of items on the grid and repeat it correctly when prompted.",
    controls: "Tap the items to reproduce the pattern.",
    goal: "Accurately recall and reproduce the pattern shown on the grid.",
  },
  'reaction-chain': {
    howToPlay: "Tap the screen as fast as you can to keep the reaction chain going. The chain will break if you don't tap in time.",
    controls: "Tap anywhere on the screen to continue the reaction chain.",
    goal: "Keep the reaction chain alive for as long as possible.",
  },
  'stack-drop': {
    howToPlay: "Precisely drop shapes to stack them without tipping the tower over. The faster you stack, the higher you can go.",
    controls: "Tap and hold to pick up a shape, then release to drop it on the tower.",
    goal: "Stack as many shapes as you can before the tower tips over.",
  },
  'dodge-blitz': {
    howToPlay: "Tilt your device to dodge obstacles and keep moving. The faster the obstacles come, the harder it is to survive.",
    controls: "Tilt your device left and right to dodge obstacles.",
    goal: "Survive as long as possible without colliding with obstacles.",
  },
  'crowd-roar': {
    howToPlay: "Blow into the microphone to make a loud crowd roar. Hold the roar as long as you can without fading.",
    controls: "Blow into the microphone to make a crowd roar.",
    goal: "Hold the crowd roar for as long as possible.",
  },
  'balance-beam': {
    howToPlay: "Keep the ball on the balance beam by tilting your device. The beam gets narrower over time, making it harder to balance.",
    controls: "Tilt your device to move the ball and keep it on the balance beam.",
    goal: "Balance the ball on the beam for as long as possible.",
  },
  'path-trace': {
    howToPlay: "Follow the on-screen line by tracing it with your finger. Don't let your finger stray from the path.",
    controls: "Use your finger to trace the on-screen line.",
    goal: "Follow the line without straying from the path.",
  },
  'pitch-match': {
    howToPlay: "Match the on-screen pitch by humming or singing the correct note. Hold the note for as long as the indicator shows.",
    controls: "Hum or sing the pitch displayed on the screen.",
    goal: "Match the on-screen pitch and hold it for the indicated duration.",
  },
  'symbol-scan': {
    howToPlay: "Quickly scan the screen and tap any symbols that match the target symbol before time runs out.",
    controls: "Tap the on-screen symbols that match the target symbol.",
    goal: "Tap all matching symbols before the time runs out.",
  },
  'neon-archer': {
    howToPlay: "Swipe to aim your neon arrow, then release at the perfect moment to hit the target.",
    controls: "Swipe to aim the arrow, then release to shoot.",
    goal: "Hit the target with your arrow.",
  },
  'ice-sculptor': {
    howToPlay: "Carefully chip away at the ice block to reveal the hidden shape inside. The faster you work, the better your score.",
    controls: "Tap and hold to chip away at the ice block.",
    goal: "Reveal the hidden shape in the ice block as quickly as possible.",
  },
  'gravity-flip': {
    howToPlay: "Tap the screen to flip the gravity and dodge the obstacles that fall in the opposite direction.",
    controls: "Tap the screen to flip the gravity.",
    goal: "Dodge the falling obstacles for as long as possible.",
  },
  'volcano-tap': {
    howToPlay: "Tap the bubbles that appear on the screen to release the pressure. If you miss too many, the volcano will erupt.",
    controls: "Tap the on-screen bubbles to release the pressure.",
    goal: "Tap the bubbles to prevent the volcano from erupting.",
  },
  'marathon-pace': {
    howToPlay: "Tilt your device to maintain a steady running pace. If you go too fast or too slow, you'll fall out of the pace.",
    controls: "Tilt your device left and right to adjust your running pace.",
    goal: "Maintain the ideal running pace for as long as possible.",
  },
  'hot-potato': {
    howToPlay: "Quickly tap the hot potato before it burns you. The potato gets hotter and hotter, so you have to act fast.",
    controls: "Tap the on-screen hot potato to pass it on.",
    goal: "Tap the hot potato before it burns you.",
  },
  'slam-dunk': {
    howToPlay: "Time your two-finger tap perfectly to slam dunk the basketball through the hoop.",
    controls: "Use two fingers to tap the screen at the right moment to slam dunk the ball.",
    goal: "Score a slam dunk by timing your tap correctly.",
  },
  'archery-draw': {
    howToPlay: "Pull back your bow, wait for the perfect moment, then release to fire your arrow at the target.",
    controls: "Tap and hold to draw the bow, then release to fire the arrow.",
    goal: "Hit the target with your arrow.",
  },
  'hockey-slap': {
    howToPlay: "Choose the angle of your hockey slap shot, then time your tap to power up and fire the puck.",
    controls: "Tap the screen to aim and power up your hockey slap shot.",
    goal: "Score a goal by timing your slap shot perfectly.",
  },
  'javelin-throw': {
    howToPlay: "Power up your javelin throw by tapping, then release at the peak of your motion to send it soaring.",
    controls: "Tap and hold to power up your javelin throw, then release to throw.",
    goal: "Throw the javelin as far as possible.",
  },
  'bowling-curve': {
    howToPlay: "Swipe to hook your bowling ball and hit the pocket for a strike.",
    controls: "Swipe to control the curve of your bowling ball.",
    goal: "Score a strike by hitting the pocket with your bowling ball.",
  },
  'swimming-stroke': {
    howToPlay: "Alternate tapping your left and right hands to simulate a swimming stroke and maintain a steady pace.",
    controls: "Tap your left and right hands alternately to swim.",
    goal: "Maintain a consistent swimming pace for as long as possible.",
  },
  'dart-board': {
    howToPlay: "Flick your finger across the screen to launch the dart. Aim for the bullseye to score the most points.",
    controls: "Flick to launch the dart.",
    goal: "Hit the bullseye to get the highest score.",
  },
  'track-sprint': {
    howToPlay: "Alternate tapping the left and right sides of the screen to sprint down the track. Stay within your lane to avoid obstacles.",
    controls: "Alternate tapping left and right to run.",
    goal: "Sprint as fast as you can without leaving your lane.",
  },
  'discus-spin': {
    howToPlay: "Spin the discus by rotating your finger on the screen, then flick to launch it as far as possible.",
    controls: "Spin to charge, then flick to release the discus.",
    goal: "Throw the discus as far as you can.",
  },
  'boxing-combo': {
    howToPlay: "Quickly tap the screen to perform a series of boxing punches, following the combo displayed on the screen.",
    controls: "Tap the screen to execute the boxing combo.",
    goal: "Complete the boxing combo as quickly as possible.",
  },
  'hoop-shot': {
    howToPlay: "Swipe the screen to launch the basketball towards the hoop. Aim for the center of the hoop to score points.",
    controls: "Swipe to shoot the basketball.",
    goal: "Score as many points as possible before time runs out.",
  },
  'penalty-kick': {
    howToPlay: "Tap the screen to power up your kick, then release at the right moment to beat the goalkeeper and score a goal.",
    controls: "Tap to charge, release to shoot the penalty kick.",
    goal: "Score as many goals as possible against the goalkeeper.",
  },
  'spiral-throw': {
    howToPlay: "Swipe the screen to throw the football, aiming to lead your receiver and avoid throwing behind them.",
    controls: "Swipe to throw the football.",
    goal: "Complete as many accurate passes as possible.",
  },
  'reflex-rally': {
    howToPlay: "Quickly tap the screen to return the ball as it bounces back and forth. Don't miss a single shot.",
    controls: "Tap to return the ball.",
    goal: "Keep the rally going for as long as possible without missing.",
  },
  'precision-putt': {
    howToPlay: "Carefully read the slope of the green, then control the power of your swing to sink the ball into the hole.",
    controls: "Adjust the power and direction of your putt.",
    goal: "Sink as many putts as possible.",
  },
  'gift-rush': {
    howToPlay: "Quickly swipe left or right to catch the falling gifts. Be careful not to miss any, or Santa will be disappointed.",
    controls: "Swipe left or right to catch the gifts.",
    goal: "Catch as many gifts as possible before time runs out.",
  },
  'snow-catch': {
    howToPlay: "Tilt your device to guide the snowflake and catch it before it falls to the ground. One missed snowflake and it's game over.",
    controls: "Tilt your device to move the snowflake.",
    goal: "Catch as many snowflakes as you can without missing any.",
  },
  'boo-blast': {
    howToPlay: "Tap the ghostly spirits as they appear on the screen, before they disappear again.",
    controls: "Tap the ghosts to blast them.",
    goal: "Tap as many ghosts as possible before time runs out.",
  },
  'cauldron-bubble': {
    howToPlay: "Blow into the microphone to keep the cauldron bubbling at the perfect level. Blow too hard or too softly, and it's BOOM!",
    controls: "Blow into the microphone to control the cauldron's bubbling.",
    goal: "Maintain the perfect bubble level for as long as possible.",
  },
  'firework-launch': {
    howToPlay: "Swipe the screen to launch the fireworks, then tap to detonate them at the perfect moment for maximum impact.",
    controls: "Swipe to launch, tap to detonate the fireworks.",
    goal: "Launch and detonate the fireworks for the best display.",
  },
  'countdown-crush': {
    howToPlay: "Quickly tap the falling objects to score points before the countdown reaches zero.",
    controls: "Tap the falling objects.",
    goal: "Score as many points as possible before the countdown ends.",
  },
  'cupid-shot': {
    howToPlay: "Aim your bow and wait for the perfect moment to release the arrow, hitting the target at the heart.",
    controls: "Aim and release the arrow at the right moment.",
    goal: "Hit the target's heart with your arrow.",
  },
  'love-note': {
    howToPlay: "Remember the sequence of taps displayed on the screen, then repeat the pattern back to complete the love note.",
    controls: "Tap the notes in the correct sequence.",
    goal: "Correctly repeat the love note pattern.",
  },
  'turkey-trot': {
    howToPlay: "Rapidly tap the screen to outrun the turkey and reach the finish line before it does.",
    controls: "Tap quickly to run faster than the turkey.",
    goal: "Reach the finish line before the turkey.",
  },
  'harvest-catch': {
    howToPlay: "Tilt your device to guide the basket and catch the falling harvest items, but be careful to avoid the Brussels sprouts.",
    controls: "Tilt your device to move the basket.",
    goal: "Catch as many harvest items as possible while avoiding the Brussels sprouts.",
  },
  'shamrock-shuffle': {
    howToPlay: "Tap the shamrocks as they appear on the screen, but be quick to avoid the falling lumps of coal.",
    controls: "Tap the shamrocks to catch them.",
    goal: "Catch as many shamrocks as possible while avoiding the coal.",
  },
  'egg-toss': {
    howToPlay: "Toss the egg up and catch it before it cracks. Tap the screen to toss, and move your finger to catch the egg.",
    controls: "Tap to toss the egg, move your finger to catch it.",
    goal: "Catch the egg without cracking it.",
  },
  'pinata-smash': {
    howToPlay: "Find the weak spot on the piñata and tap rapidly to break it open and collect the treats inside.",
    controls: "Tap the screen rapidly to smash the piñata.",
    goal: "Break open the piñata and collect the treats.",
  },
  'flower-bouquet': {
    howToPlay: "Catch the falling flower petals and arrange them into a beautiful bouquet. Tap the screen to catch the petals.",
    controls: "Tap the screen to catch falling flower petals.",
    goal: "Catch and arrange the petals into a bouquet.",
  },
  'bbq-master': {
    howToPlay: "Flip the burgers on the grill to cook them perfectly without burning them. Tilt your device to flip the burgers.",
    controls: "Tilt your device left and right to flip the burgers.",
    goal: "Cook the burgers to perfection without burning them.",
  },
  'sparkler-draw': {
    howToPlay: "Use the sparkler to draw shapes and patterns in the air. Tilt your device to move the sparkler.",
    controls: "Tilt your device to move the sparkler and draw in the air.",
    goal: "Draw intricate and sparkling patterns with the sparkler.",
  },
  'pencil-pack': {
    howToPlay: "Sort the pencils by color and pack them neatly into the case. Tap and drag the pencils to sort and pack them.",
    controls: "Tap and drag the pencils to sort and pack them.",
    goal: "Sort and pack all the pencils neatly into the case.",
  },
  'diya-light': {
    howToPlay: "Light the diyas in the correct order by tapping them. The sequence gets faster as you progress.",
    controls: "Tap the diyas in the correct order to light them.",
    goal: "Light all the diyas in the correct sequence before time runs out.",
  },
  'dreidel-spin': {
    howToPlay: "Flick the dreidel hard to make it spin. Tap the screen to keep it spinning as long as possible.",
    controls: "Flick the dreidel to spin it, tap the screen to keep it spinning.",
    goal: "Keep the dreidel spinning for as long as possible.",
  },
  'dragon-parade': {
    howToPlay: "Use multiple fingers to control the dragon's movements and make it dance through the parade.",
    controls: "Use multiple fingers to control the dragon's movements.",
    goal: "Guide the dragon through the parade and make it dance.",
  },
  'bead-catch': {
    howToPlay: "Tilt your device to catch the falling beads and collect them in the basket.",
    controls: "Tilt your device left and right to catch the beads.",
    goal: "Catch as many beads as possible in the basket.",
  },
  'lantern-float': {
    howToPlay: "Blow into the microphone to inflate the lanterns and watch them float up into the sky.",
    controls: "Blow into the microphone to inflate the lanterns.",
    goal: "Inflate all the lanterns and watch them float up.",
  },
  'taco-toss': {
    howToPlay: "Catch the falling taco ingredients and assemble them into a delicious taco. Tap the screen to catch the ingredients.",
    controls: "Tap the screen to catch the taco ingredients.",
    goal: "Catch all the ingredients and assemble a complete taco.",
  },
  'basket-weave': {
    howToPlay: "Swipe the screen to weave the basket strands, making sure not to drop any.",
    controls: "Swipe the screen to weave the basket strands.",
    goal: "Weave the basket strands without dropping any.",
  },
  'clover-path': {
    howToPlay: "Trace the path of the lucky clovers by dragging your finger along the screen. Don't stray from the path.",
    controls: "Drag your finger to trace the clover path.",
    goal: "Follow the lucky clover path without straying off.",
  },
  'signal-boost': {
    howToPlay: "Hum a steady tone into the microphone to keep the signal tower alive and boosting.",
    controls: "Hum a steady tone into the microphone.",
    goal: "Maintain a steady hum to keep the signal tower alive.",
  },
  'crystal-grow': {
    howToPlay: "Breathe steadily into the microphone to grow the crystal. Erratic breathing will cause it to crumble.",
    controls: "Breathe steadily into the microphone.",
    goal: "Grow the crystal by maintaining steady breathing.",
  },
  'echo-clap': {
    howToPlay: "Clap in time with the echoing clap pattern. The pattern gets faster as you progress.",
    controls: "Clap in time with the echoing clap pattern.",
    goal: "Keep up with the increasingly fast clap pattern.",
  },
  'solar-charge': {
    howToPlay: "Stay silent to charge the solar panel. Any noise will drain the charge.",
    controls: "Remain silent to charge the solar panel.",
    goal: "Charge the solar panel by staying completely silent.",
  },
  'aurora-wave': {
    howToPlay: "Breathe slowly and steadily into the microphone to paint the aurora waves. Erratic breathing will break the pattern.",
    controls: "Breathe slowly and steadily into the microphone.",
    goal: "Maintain steady breathing to paint the aurora waves.",
  },
  'dragon-breath': {
    howToPlay: "Blow hard into the microphone to unleash the dragon's fiery breath.",
    controls: "Blow hard into the microphone.",
    goal: "Unleash the dragon's fiery breath.",
  },
  'voice-sculpt': {
    howToPlay: "Hum into the microphone to shape the on-screen clay. Change your pitch and volume to sculpt the clay to the desired form before time runs out.",
    controls: "Hum into the microphone to control the clay.",
    goal: "Sculpt the clay to the desired form within the time limit.",
  },
  'echo-match': {
    howToPlay: "Listen to the echo and hold the note to match it. Repeat the echoes correctly to progress to the next level.",
    controls: "Hold the note to match the echo.",
    goal: "Correctly match all the echoes before time runs out.",
  },
  'howl-wolf': {
    howToPlay: "Find the correct pitch to howl and call the wolf pack. Howl at the right frequency to attract the wolves.",
    controls: "Howl into the microphone to call the wolf pack.",
    goal: "Attract all the wolves in the pack before time runs out.",
  },
  'beat-box': {
    howToPlay: "Drop the beat by tapping the screen to the rhythm. Keep the beat going as long as possible by tapping in time.",
    controls: "Tap the screen to the rhythm to keep the beat going.",
    goal: "Maintain the beat for as long as possible.",
  },
  'hum-maze': {
    howToPlay: "Hum into the microphone to navigate through the on-screen maze. Change your pitch to move the character up and down to avoid obstacles.",
    controls: "Hum into the microphone to control the character's movement.",
    goal: "Reach the end of the maze before time runs out.",
  },
  'chant-power': {
    howToPlay: "Hold a continuous chant to charge the on-screen power meter. Maintain the chant as long as possible to fill the meter and win.",
    controls: "Hold a continuous chant into the microphone to charge the power meter.",
    goal: "Fill the power meter by maintaining the chant before time runs out.",
  },
  'whistle-launch': {
    howToPlay: "Whistle into the microphone to launch the on-screen object. Change the pitch of your whistle to steer the object and hit the targets.",
    controls: "Whistle into the microphone to launch and steer the object.",
    goal: "Hit as many targets as possible before time runs out.",
  },
  'vocal-shield': {
    howToPlay: "Sing a note into the microphone to create a vocal shield. Hold the note to maintain the shield and block incoming projectiles.",
    controls: "Sing a note into the microphone to create and hold the vocal shield.",
    goal: "Block all incoming projectiles before time runs out.",
  },
  'breath-sculpt': {
    howToPlay: "Control your breath to shape the on-screen sculpture. Breathe slowly or quickly to manipulate the sculpture's form.",
    controls: "Control your breath (inhale/exhale) to shape the sculpture.",
    goal: "Sculpt the on-screen object to the desired form within the time limit.",
  },
  'frequency-tune': {
    howToPlay: "Find the target frequency and hold it by humming or singing the note. Maintain the frequency to progress through the levels.",
    controls: "Hum or sing the target frequency to progress.",
    goal: "Hold the target frequency for the required duration.",
  },
  'lung-capacity': {
    howToPlay: "Take a deep breath and hold the note for as long as possible. See how long you can sustain the note before running out of air.",
    controls: "Take a deep breath and hold the note.",
    goal: "Hold the note for as long as possible.",
  },
  'sound-waves': {
    howToPlay: "Shout the target frequency to shatter the on-screen walls. Adjust your volume and pitch to hit the correct frequency and destroy the obstacles.",
    controls: "Shout the target frequency into the microphone.",
    goal: "Shatter all the walls before time runs out.",
  },
  'sing-along': {
    howToPlay: "Match the on-screen note by singing or humming. Hold the note perfectly to progress to the next level.",
    controls: "Sing or hum to match the on-screen note.",
    goal: "Match all the notes correctly before time runs out.",
  },
  'morse-tap': {
    howToPlay: "Tap the screen in the rhythm of Morse code to send the message. Listen carefully and tap the code correctly to transmit the message.",
    controls: "Tap the screen to send the Morse code message.",
    goal: "Transmit the Morse code message correctly before time runs out.",
  },
  'morse-decode': {
    howToPlay: "Watch the Morse code flashes and decode the letter being transmitted. Identify the letter before time runs out.",
    controls: "Observe the Morse code flashes and enter the corresponding letter.",
    goal: "Decode the Morse code letter correctly before time runs out.",
  },
  'code-breaker': {
    howToPlay: "Memorize the code, then hide it and enter the correct sequence before time runs out.",
    controls: "Tap the screen to enter the code sequence.",
    goal: "Enter the correct code sequence within the time limit.",
  },
  'pulse-jump': {
    howToPlay: "Tap the screen in rhythm with the pulsing beat. Mistime your taps and you'll fall!",
    controls: "Tap the screen in time with the beat.",
    goal: "Tap the screen in perfect rhythm with the beat for as long as possible.",
  },
  'domino-chain': {
    howToPlay: "Tap the first domino at the perfect moment to start a chain reaction. Time your tap precisely to keep the chain going.",
    controls: "Tap the first domino at the right moment.",
    goal: "Maintain the domino chain for as long as possible.",
  },
  'number-crunch': {
    howToPlay: "Solve the math problem and tap the correct answer quickly before time runs out.",
    controls: "Tap the screen to select the correct answer.",
    goal: "Solve as many math problems correctly within the time limit.",
  },
  'mirror-mind': {
    howToPlay: "Move both hands in a mirrored, synchronized pattern. Keep your hands moving in perfect sync.",
    controls: "Move both hands in a mirrored, synchronized pattern.",
    goal: "Maintain the mirrored, synchronized hand movements for as long as possible.",
  },
  'number-path': {
    howToPlay: "Tap the numbers in ascending order as fast as you can. The faster you reach the highest number, the higher your score.",
    controls: "Tap the numbers to progress along the path.",
    goal: "Reach the highest number before time runs out.",
  },
  'logic-gate': {
    howToPlay: "Quickly wire the circuit by tapping the logic gates to get the desired output. Strategize the best path to solve the puzzle.",
    controls: "Tap the logic gates to build the circuit.",
    goal: "Correctly wire the circuit to get the target output.",
  },
  'binary-decode': {
    howToPlay: "Flip the bits to reveal the hidden number. Decipher the binary code as quickly as possible.",
    controls: "Tap the bits to flip them and find the hidden number.",
    goal: "Decode the binary number within the time limit.",
  },
  'attention-switch': {
    howToPlay: "Focus on two tasks simultaneously. Quickly switch your attention between the two streams to complete both successfully.",
    controls: "Tap the objects in each stream as they appear.",
    goal: "Complete both tasks before the time runs out.",
  },
  'face-memory': {
    howToPlay: "Memorize the faces shown, then quickly identify them when they reappear in a grid. Test your visual memory skills.",
    controls: "Tap the faces you recognize from the initial set.",
    goal: "Correctly identify all the faces within the time limit.",
  },
  'inference-trail': {
    howToPlay: "Observe the clues and use your deductive reasoning to determine the final answer. Follow the logical trail to reach the solution.",
    controls: "Tap the clues and options to progress through the puzzle.",
    goal: "Arrive at the correct conclusion before the time runs out.",
  },
  'spatial-map': {
    howToPlay: "Study the map closely, then answer the questions about its features as quickly as possible. Demonstrate your spatial awareness and memory.",
    controls: "Tap the options to answer the questions about the map.",
    goal: "Correctly answer all the questions within the time limit.",
  },
  'neon-chess': {
    howToPlay: "Plan your move carefully and execute it with precision. Think like a chess master to outmaneuver your opponent in this neon-themed challenge.",
    controls: "Tap the chess piece you want to move and then its destination square.",
    goal: "Make the best move to win the game.",
  },
  'shape-rotate': {
    howToPlay: "Visualize the shape rotating in your mind, then quickly tap the matching shape in the grid. Test your spatial reasoning skills.",
    controls: "Tap the shape that matches the rotated version.",
    goal: "Correctly identify the matching shape before the time runs out.",
  },
  'type-speed': {
    howToPlay: "Type the words that appear on the screen as quickly as you can. Demonstrate your typing prowess against the ticking clock.",
    controls: "Use the keyboard to type the words.",
    goal: "Type as many words as possible before the time expires.",
  },
  'bubble-burst': {
    howToPlay: "Pinch the bubble to the perfect size before it bursts. Carefully control your touch to find the sweet spot.",
    controls: "Pinch the bubble to adjust its size.",
    goal: "Burst the bubble at the ideal size.",
  },
  'tower-stack': {
    howToPlay: "Carefully stack the blocks to build the tallest tower without it toppling over. Use your hand-eye coordination and precision.",
    controls: "Tap and drag the blocks to stack them.",
    goal: "Construct the highest tower possible.",
  },
  'bounce-pass': {
    howToPlay: "Angle the ball's bounce to make the perfect pass through the hoop. Demonstrate your spatial awareness and timing skills.",
    controls: "Tap and drag to adjust the ball's trajectory.",
    goal: "Successfully pass the ball through the hoop.",
  },
  'gear-grind': {
    howToPlay: "Mesh the gears together to keep the machine spinning. Maintain the rhythm and avoid any disruption.",
    controls: "Tap and drag the gears to connect them.",
    goal: "Keep the gears spinning continuously.",
  },
  'thread-needle': {
    howToPlay: "Carefully guide the thread through the needle's eye. Steady hands and precision are key in this delicate task.",
    controls: "Tap and drag the thread to guide it through the needle.",
    goal: "Successfully thread the needle.",
  },
  'jigsaw-rush': {
    howToPlay: "Quickly assemble the jigsaw puzzle before time runs out. Observe the pieces and plan your moves wisely.",
    controls: "Tap and drag the puzzle pieces to snap them into place.",
    goal: "Complete the jigsaw puzzle as fast as possible.",
  },
  'cable-wrap': {
    howToPlay: "Neatly wrap the cable without creating any tangles or knots. Maintain control and dexterity to keep the cable tidy.",
    controls: "Tap and drag the cable to wrap it.",
    goal: "Wrap the cable without any tangles.",
  },
  'magnet-maze': {
    howToPlay: "Navigate the maze using the magnetic forces to guide your path. Attract and repel the magnets to find the safest route.",
    controls: "Tap and drag the magnets to manipulate the path.",
    goal: "Reach the end of the maze before time runs out.",
  },
  'cosmic-catch': {
    howToPlay: "Swipe the glowing cosmic stars before they fade away. Showcase your quick reflexes and hand-eye coordination.",
    controls: "Swipe the stars to catch them.",
    goal: "Catch as many stars as possible.",
  },
  'wormhole-dive': {
    howToPlay: "Dive through the wormhole and survive the cosmic journey. Maintain your focus and agility to navigate the treacherous path.",
    controls: "Tap and tilt to steer through the wormhole.",
    goal: "Survive the wormhole dive for as long as possible.",
  },
  'dream-catch': {
    howToPlay: "Float through the dream landscape and tap on the floating fragments to catch them before they disappear.",
    controls: "Tilt your device to move and tap the fragments to catch them.",
    goal: "Catch as many fragments as possible before time runs out.",
  },
  'sound-garden': {
    howToPlay: "Tap on the growing flowers to make them bloom and play different musical notes. Grow the garden to create a harmonious melody.",
    controls: "Tap on the flowers to make them bloom and grow the garden.",
    goal: "Create a complete musical composition by growing the garden.",
  },
  'curling-sweep': {
    howToPlay: "Sweep the curling stone across the ice to guide it into the target zone. Control the power and direction of your sweeps to score points.",
    controls: "Swipe left/right to adjust the stone's direction, and swipe up/down to control the sweeping power.",
    goal: "Score as many points as possible by getting the stone into the target zone.",
  },
  'rowing-rhythm': {
    howToPlay: "Sync your rowing strokes with the on-screen rhythm to propel your boat forward. Time your taps and swipes to the beat for maximum speed.",
    controls: "Tap and swipe in time with the rhythm to row your boat.",
    goal: "Row as far as you can before time runs out.",
  },
  'baseball-swing': {
    howToPlay: "Watch the pitch carefully and time your swing to make solid contact with the ball. Tap at the right moment to send the ball soaring.",
    controls: "Tap to swing your bat when the pitch reaches the strike zone.",
    goal: "Hit as many home runs as you can.",
  },
  'karate-chop': {
    howToPlay: "Focus your energy and chop the correct target zone when it appears. Precisely time your karate chops to earn points.",
    controls: "Tap the target zone when it appears.",
    goal: "Chop the most targets before time runs out.",
  },
  'pole-vault': {
    howToPlay: "Run, plant your pole, and time your jump to clear the bar. Adjust your angle and power to soar over the obstacle.",
    controls: "Tap to plant the pole, and swipe up to jump.",
    goal: "Clear the highest bar possible.",
  },
  'table-tennis': {
    howToPlay: "Precisely time your returns to keep the rally going. Anticipate your opponent's shots and react quickly to send the ball back.",
    controls: "Tap to return the ball, and swipe to add spin.",
    goal: "Keep the rally going for as long as possible.",
  },
  'gymnast-beam': {
    howToPlay: "Balance on the beam and perform a series of acrobatic moves. Maintain your focus and stick the landing to earn high scores.",
    controls: "Tap and swipe to execute different gymnastic routines on the beam.",
    goal: "Earn the highest score by performing a flawless routine.",
  },
  'pixel-skate': {
    howToPlay: "Flick your finger to perform various tricks and combos. Chain together multiple tricks to build up your score.",
    controls: "Flick your finger in different directions to perform tricks.",
    goal: "Achieve the highest combo score before time runs out.",
  },
  'surf-ride': {
    howToPlay: "Tilt your device to balance on the surfboard and swipe to perform tricks. Ride the wave and show off your skills.",
    controls: "Tilt your device to balance and swipe to perform tricks.",
    goal: "Ride the wave and perform as many tricks as possible.",
  },
  'ski-slalom': {
    howToPlay: "Weave your way through the gates, maintaining your speed and control. Time your turns and avoid missing any gates to achieve the best time.",
    controls: "Tilt your device left and right to navigate the gates.",
    goal: "Complete the slalom course with the fastest time.",
  },
  'mirror-dance': {
    howToPlay: "Follow the movements on the mirror and sync your dance steps to the beat. Maintain the rhythm and precision to earn points.",
    controls: "Tap and swipe to match the dance moves shown on the mirror.",
    goal: "Score as many points as possible by precisely following the dance moves.",
  },
  'sand-pour': {
    howToPlay: "Carefully pour the sand into the glass, making sure not to spill any. Control the flow and fill the glass to the correct level.",
    controls: "Tilt your device to pour the sand into the glass.",
    goal: "Fill the glass to the exact level without spilling any sand.",
  },
  'color-blend': {
    howToPlay: "Swipe to blend the colors and match the target hue displayed on the screen. Precisely adjust the mix to hit the perfect blend.",
    controls: "Swipe left/right to blend the colors.",
    goal: "Blend the colors to match the target hue.",
  },
  'echo-tap': {
    howToPlay: "Listen carefully to the rhythm pattern and repeat it by tapping the screen. Memorize the sequence and perfectly echo the taps.",
    controls: "Tap the screen to repeat the rhythm pattern.",
    goal: "Correctly repeat the rhythm pattern.",
  },
  'heat-map': {
    howToPlay: "Observe the image and quickly identify the areas that draw your attention first. Tap the hotspots to reveal the heat map.",
    controls: "Tap the areas of the image that catch your eye.",
    goal: "Uncover the heat map by tapping the most visually striking parts of the image.",
  },
  'trust-fall': {
    howToPlay: "Maintain focus and let go at the precise moment to safely fall into the arms of your teammates. Timing is crucial to this act of trust.",
    controls: "Hold and release the screen to execute the trust fall.",
    goal: "Successfully complete the trust fall at the right moment.",
  },
  'spark-chain': {
    howToPlay: "Ignite the first spark and watch it spread through the chain. Carefully time your taps to maximize the spread and coverage.",
    controls: "Tap the screen to ignite the first spark and keep the chain going.",
    goal: "Spread the spark to cover as much of the screen as possible.",
  },
  'crowd-pulse': {
    howToPlay: "Sense the energy of the crowd and tap the screen in sync with the collective rhythm. Feel the pulse of the room and keep the momentum going.",
    controls: "Tap the screen to the beat of the crowd's energy.",
    goal: "Maintain the crowd's energy by tapping in time with the collective rhythm.",
  },
};