// ─── Types ────────────────────────────────────────────────────────────────────

export type GameCategory = 'skill' | 'sports' | 'holiday' | 'cognitive' | 'breath';

export type Industry = 'cpg' | 'technology' | 'healthcare' | 'finance' | 'food_bev' | 'sports' | 'retail' | 'automotive';

export interface Game {
  id: string;
  title: string;
  tagline: string;
  href: string;
  accentColor: string;
  duration: string;
  icon: string; // Material Symbol name
  category: GameCategory;
  industries: Industry[];
  measures?: string[]; // Ether behavioral signals — populated at runtime from measures.ts
}

// ─── Game Data ────────────────────────────────────────────────────────────────

export const SKILL_GAMES: Game[] = [
  { id: 'paint-splash',    title: 'Paint Splash',    tagline: 'Shake and tilt to splatter paint. Cover the canvas!',     href: '/games/paint-splash',    accentColor: '#f43f5e', duration: '45s', icon: 'brush',               category: 'skill',     industries: ['cpg', 'retail', 'technology']            },
  { id: 'web-weave',       title: 'Web Weave',       tagline: 'Drag between anchors to weave your web. Catch flies!',     href: '/games/web-weave',       accentColor: '#64748b', duration: '60s', icon: 'account_tree',        category: 'skill',     industries: ['technology', 'healthcare', 'retail']     },
  { id: 'treasure-dive',   title: 'Treasure Dive',   tagline: 'Tilt to steer your diver. Grab treasure, dodge sharks!',  href: '/games/treasure-dive',   accentColor: '#0ea5e9', duration: '60s', icon: 'scuba_diving',        category: 'skill',     industries: ['sports', 'cpg', 'retail']                },
  { id: 'frog-leap',       title: 'Frog Leap',       tagline: 'Tap left/right to leap to lily pads. Miss = splash!',     href: '/games/frog-leap',       accentColor: '#22c55e', duration: '45s', icon: 'sports',              category: 'skill',     industries: ['sports', 'food_bev', 'cpg']              },
  { id: 'wire-cross',      title: 'Wire Cross',       tagline: "Thread the ring. Don't touch the wire.",      href: '/games/wire-cross',      accentColor: '#00e5ff', duration: '45s', icon: 'electric_bolt',       category: 'skill',     industries: ['technology', 'automotive', 'healthcare'] },
  { id: 'balloon-pop',     title: 'Balloon Pop',      tagline: 'Pinch to pop before they overflow!',          href: '/games/balloon-pop',     accentColor: '#f43f5e', duration: '30s', icon: 'expand',              category: 'skill',     industries: ['cpg', 'retail', 'food_bev']              },
  { id: 'slingshot-smash', title: 'Slingshot Smash',  tagline: 'Stretch it. Aim it. Smash it.',               href: '/games/slingshot-smash', accentColor: '#f97316', duration: '45s', icon: 'sports_handball',     category: 'skill',     industries: ['sports', 'cpg', 'retail']                },
  { id: 'ripple-tap',      title: 'Ripple Tap',       tagline: 'Tap the peak. Not too early, not late.',      href: '/games/ripple-tap',      accentColor: '#06b6d4', duration: '30s', icon: 'waves',               category: 'skill',     industries: ['technology', 'healthcare', 'finance']    },
  { id: 'pendulum-swing',  title: 'Pendulum Swing',   tagline: "Keep the rhythm. Don't let it stop.",         href: '/games/pendulum-swing',  accentColor: '#a855f7', duration: '60s', icon: 'pending',             category: 'skill',     industries: ['technology', 'finance', 'automotive']    },
  { id: 'node-connect',    title: 'Node Connect',     tagline: 'Link the dots. Cross nothing.',               href: '/games/node-connect',    accentColor: '#10b981', duration: '45s', icon: 'account_tree',        category: 'skill',     industries: ['technology', 'finance', 'healthcare']    },
  { id: 'orbit-launch',    title: 'Orbit Launch',     tagline: 'Nail the angle. Own the orbit.',              href: '/games/orbit-launch',    accentColor: '#6366f1', duration: '45s', icon: 'rocket_launch',       category: 'skill',     industries: ['technology', 'automotive', 'finance']    },
  { id: 'speed-sort',      title: 'Speed Sort',       tagline: 'Left or right. Think fast.',                  href: '/games/speed-sort',      accentColor: '#facc15', duration: '30s', icon: 'sort',                category: 'skill',     industries: ['retail', 'finance', 'cpg']               },
  { id: 'spring-leap',     title: 'Spring Leap',      tagline: 'Hold to charge. Release to fly.',             href: '/games/spring-leap',     accentColor: '#4ade80', duration: '45s', icon: 'compress',            category: 'skill',     industries: ['sports', 'retail', 'technology']         },
  { id: 'crystal-catch',   title: 'Crystal Catch',    tagline: "Tilt and collect. Don't shatter them.",       href: '/games/crystal-catch',   accentColor: '#818cf8', duration: '45s', icon: 'diamond',             category: 'skill',     industries: ['retail', 'cpg', 'finance']               },
  { id: 'wobble-stack',    title: 'Wobble Stack',     tagline: 'Keep it balanced. It gets worse.',            href: '/games/wobble-stack',    accentColor: '#fb923c', duration: '60s', icon: 'layers',              category: 'skill',     industries: ['cpg', 'retail', 'food_bev']              },
  { id: 'chain-reaction',  title: 'Chain Reaction',   tagline: 'One tap. Maximum chaos.',                     href: '/games/chain-reaction',  accentColor: '#fb7185', duration: '30s', icon: 'auto_awesome',        category: 'skill',     industries: ['technology', 'cpg', 'sports']            },
  { id: 'pixel-paint',     title: 'Pixel Paint',      tagline: 'Speed-paint the pattern. Go!',                href: '/games/pixel-paint',     accentColor: '#f472b6', duration: '30s', icon: 'brush',               category: 'skill',     industries: ['retail', 'technology', 'cpg']            },
  { id: 'drop-zone',       title: 'Drop Zone',        tagline: 'Release at the right moment.',                href: '/games/drop-zone',       accentColor: '#22d3ee', duration: '45s', icon: 'arrow_downward',      category: 'skill',     industries: ['retail', 'cpg', 'food_bev']              },
  { id: 'laser-guide',     title: 'Laser Guide',      tagline: 'Reflect the beam. Hit the target.',           href: '/games/laser-guide',     accentColor: '#dc2626', duration: '45s', icon: 'flashlight_on',       category: 'skill',     industries: ['technology', 'finance', 'automotive']    },
  { id: 'friction-slide',  title: 'Friction Slide',   tagline: 'Flick with precision. Stop on target.',       href: '/games/friction-slide',  accentColor: '#0ea5e9', duration: '45s', icon: 'drag_pan',            category: 'skill',     industries: ['sports', 'retail', 'cpg']                },
  { id: 'gravity-well',    title: 'Gravity Well',     tagline: "Orbit the well. Don't get pulled in.",        href: '/games/gravity-well',    accentColor: '#7c3aed', duration: '60s', icon: 'lens',                category: 'skill',     industries: ['technology', 'finance', 'automotive']    },
  { id: 'tilt-maze',       title: 'Tilt Maze',       tagline: 'Roll the ball with your body',                href: '/games/tilt-maze',       accentColor: '#a855f7', duration: '60s', icon: 'explore',             category: 'skill',     industries: ['technology', 'retail', 'automotive']    },
  { id: 'whisper-bomb',    title: 'Whisper Bomb',    tagline: 'Stay silent. Defuse the bomb.',               href: '/games/whisper-bomb',    accentColor: '#ef4444', duration: '30s', icon: 'bomb',                category: 'breath',    industries: ['cpg', 'food_bev', 'technology']          },
  { id: 'breath-rider',    title: 'Breath Rider',    tagline: 'Fly with your breath',                        href: '/games/breath-rider',    accentColor: '#3b82f6', duration: '45s', icon: 'air',                 category: 'breath',    industries: ['healthcare', 'technology', 'retail']     },
  { id: 'steady-hand',     title: 'Steady Hand',     tagline: 'Hold perfectly still. We dare you.',         href: '/games/steady-hand',     accentColor: '#22c55e', duration: '30s', icon: 'ads_click',           category: 'skill',     industries: ['healthcare', 'technology', 'automotive'] },
  { id: 'tunnel',          title: 'Infinite Tunnel', tagline: "Dodge the rings. Don't crash.",               href: '/games/tunnel',          accentColor: '#00ffff', duration: '60s', icon: 'bolt',                category: 'skill',     industries: ['technology', 'automotive', 'retail']     },
  { id: 'pulse-sphere',    title: 'Pulse Sphere',    tagline: 'Touch. Move. Breathe. Watch it respond.',     href: '/games/pulse-sphere',    accentColor: '#a855f7', duration: '60s', icon: 'pulmonology',         category: 'breath',    industries: ['healthcare', 'technology', 'cpg']        },
  { id: 'shadow-tap',      title: 'Shadow Tap',      tagline: "Tap what you see. Before it's gone.",         href: '/games/shadow-tap',      accentColor: '#64748b', duration: '45s', icon: 'dark_mode',           category: 'cognitive', industries: ['technology', 'retail', 'cpg']            },
  { id: 'color-cascade',   title: 'Color Cascade',   tagline: 'Match the color. Match the speed.',           href: '/games/color-cascade',   accentColor: '#f43f5e', duration: '45s', icon: 'palette',             category: 'cognitive', industries: ['cpg', 'food_bev', 'retail']              },
  { id: 'equation-tap',    title: 'Equation Tap',     tagline: 'Solve it. Tap it. Beat the clock.',           href: '/games/equation-tap',    accentColor: '#facc15', duration: '45s', icon: 'calculate',           category: 'cognitive', industries: ['finance','technology','healthcare']    },
  { id: 'color-word',      title: 'Color Word',       tagline: 'Ignore the meaning. Trust your eyes.',        href: '/games/color-word',      accentColor: '#f43f5e', duration: '30s', icon: 'text_fields',         category: 'cognitive', industries: ['cpg','retail','technology']            },
  { id: 'visual-search',   title: 'Visual Search',    tagline: 'Find it. Tap it. Before the horde.',          href: '/games/visual-search',   accentColor: '#10b981', duration: '45s', icon: 'search',              category: 'cognitive', industries: ['retail','cpg','technology']            },
  { id: 'odd-one-out',     title: 'Odd One Out',      tagline: "Spot what doesn't belong. Quick!",            href: '/games/odd-one-out',     accentColor: '#f97316', duration: '45s', icon: 'find_in_page',        category: 'cognitive', industries: ['retail','cpg','technology']            },
  { id: 'pattern-predict', title: 'Pattern Predict',  tagline: 'What comes next? You tell me.',               href: '/games/pattern-predict', accentColor: '#14b8a6', duration: '45s', icon: 'trending_up',         category: 'cognitive', industries: ['finance','technology','cpg']           },
  { id: 'reflex-grid',     title: 'Reflex Grid',      tagline: 'Tap the flash. Never miss twice.',            href: '/games/reflex-grid',     accentColor: '#ef4444', duration: '30s', icon: 'grid_on',             category: 'cognitive', industries: ['sports','technology','cpg']            },
  { id: 'sequence-unlock', title: 'Sequence Unlock',  tagline: 'Watch the lights. Repeat them.',              href: '/games/sequence-unlock', accentColor: '#a855f7', duration: '60s', icon: 'pattern',             category: 'cognitive', industries: ['technology','finance','healthcare']    },
  { id: 'word-flash',      title: 'Word Flash',       tagline: 'Read it. Remember it. Recall it.',            href: '/games/word-flash',      accentColor: '#ec4899', duration: '60s', icon: 'flash_on',            category: 'cognitive', industries: ['retail','cpg','healthcare']            },
  { id: 'rhythm-repeat',   title: 'Rhythm Repeat',    tagline: 'Hear the beat. Play it back.',                href: '/games/rhythm-repeat',   accentColor: '#f59e0b', duration: '60s', icon: 'music_note',          category: 'cognitive', industries: ['cpg','retail','food_bev']              },
  { id: 'category-clash',  title: 'Category Clash',   tagline: 'Sort it fast. Categories clash!',             href: '/games/category-clash',  accentColor: '#fb923c', duration: '30s', icon: 'category',            category: 'cognitive', industries: ['retail','cpg','food_bev']              },
  { id: 'memory-grid',     title: 'Memory Grid',     tagline: 'Remember the pattern. Repeat it.',            href: '/games/memory-grid',     accentColor: '#8b5cf6', duration: '60s', icon: 'grid_view',           category: 'cognitive', industries: ['finance', 'technology', 'healthcare']    },
  { id: 'reaction-chain',  title: 'Reaction Chain',  tagline: 'Tap fast. Keep the chain alive.',              href: '/games/reaction-chain',  accentColor: '#facc15', duration: '45s', icon: 'link',                category: 'cognitive', industries: ['technology', 'sports', 'cpg']            },
  { id: 'stack-drop',      title: 'Stack Drop',      tagline: "Drop it. Stack it. Don't tip it.",             href: '/games/stack-drop',      accentColor: '#f97316', duration: '60s', icon: 'layers',              category: 'skill',     industries: ['cpg', 'retail', 'food_bev']              },
  { id: 'dodge-blitz',     title: 'Dodge Blitz',     tagline: "Tilt to survive. Don't stop moving.",         href: '/games/dodge-blitz',     accentColor: '#06b6d4', duration: '45s', icon: 'swap_horiz',          category: 'skill',     industries: ['technology', 'sports', 'automotive']     },
  { id: 'crowd-roar',      title: 'Crowd Roar',      tagline: "Roar loud. Hold it. Don't fade.",              href: '/games/crowd-roar',      accentColor: '#ef4444', duration: '45s', icon: 'radio',               category: 'breath',    industries: ['sports', 'cpg', 'food_bev']              },
  { id: 'balance-beam',    title: 'Balance Beam',    tagline: 'Keep the ball on the beam. Stay still.',       href: '/games/balance-beam',    accentColor: '#f59e0b', duration: '60s', icon: 'balance',             category: 'skill',     industries: ['sports', 'healthcare', 'technology']     },
  { id: 'path-trace',      title: 'Path Trace',      tagline: "Follow the line. Don't stray.",                href: '/games/path-trace',      accentColor: '#e879f9', duration: '45s', icon: 'edit',                category: 'skill',     industries: ['technology', 'automotive', 'finance']    },
  { id: 'pitch-match',     title: 'Pitch Match',     tagline: 'Hit the note. Hold it. Feel it.',               href: '/games/pitch-match',     accentColor: '#34d399', duration: '45s', icon: 'music_note',          category: 'breath',    industries: ['cpg', 'food_bev', 'retail']              },
  { id: 'symbol-scan',     title: 'Symbol Scan',     tagline: 'Find it. Tap it. Before the clock runs out.',  href: '/games/symbol-scan',     accentColor: '#10b981', duration: '60s', icon: 'manage_search',       category: 'cognitive', industries: ['finance', 'technology', 'healthcare']    },
  { id: 'neon-archer',   title: 'Neon Archer',   tagline: 'Swipe to aim. Release at the perfect moment.',  href: '/games/neon-archer',   accentColor: '#00ffcc', duration: '60s', icon: 'sports_martial_arts', category: 'sports',    industries: ['sports', 'technology', 'retail']   },
  { id: 'ice-sculptor',  title: 'Ice Sculptor',  tagline: 'Chip away ice. Reveal the hidden shape.',        href: '/games/ice-sculptor',  accentColor: '#93c5fd', duration: '45s', icon: 'ac_unit',             category: 'skill',     industries: ['retail', 'cpg', 'technology']      },
  { id: 'gravity-flip',  title: 'Gravity Flip',  tagline: 'Tap to flip gravity. Dodge everything.',         href: '/games/gravity-flip',  accentColor: '#8b5cf6', duration: '60s', icon: 'swap_vert',           category: 'skill',     industries: ['technology', 'sports', 'retail']   },
  { id: 'volcano-tap',   title: 'Volcano Tap',   tagline: 'Pop the bubbles. Miss three — eruption!',        href: '/games/volcano-tap',   accentColor: '#ef4444', duration: '45s', icon: 'local_fire_department', category: 'skill',   industries: ['cpg', 'food_bev', 'sports']        },
  { id: 'marathon-pace', title: 'Marathon Pace', tagline: 'Tilt to pace. Stay in the zone.',                href: '/games/marathon-pace', accentColor: '#22c55e', duration: '60s', icon: 'directions_run',      category: 'skill',     industries: ['sports', 'healthcare', 'technology'] },
  { id: 'hot-potato',    title: 'Hot Potato',    tagline: 'Tap it away before it burns you.',               href: '/games/hot-potato',    accentColor: '#f97316', duration: '30s', icon: 'whatshot',            category: 'skill',     industries: ['food_bev', 'cpg', 'retail']        },
];

export const SPORTS_GAMES: Game[] = [
  { id: 'slam-dunk',       title: 'Slam Dunk',        tagline: 'Two fingers. One moment. Go!',                href: '/games/slam-dunk',       accentColor: '#f97316', duration: '45s', icon: 'sports_basketball', category: 'sports', industries: ['sports', 'cpg', 'retail']           },
  { id: 'archery-draw',    title: 'Archery Draw',     tagline: 'Pull back. Wait. Release.',                   href: '/games/archery-draw',    accentColor: '#16a34a', duration: '60s', icon: 'target',            category: 'sports', industries: ['sports', 'cpg', 'retail']           },
  { id: 'hockey-slap',     title: 'Hockey Slap',      tagline: 'Pick your angle. Fire away.',                 href: '/games/hockey-slap',     accentColor: '#3b82f6', duration: '45s', icon: 'sports_hockey',     category: 'sports', industries: ['sports', 'cpg', 'food_bev']         },
  { id: 'javelin-throw',   title: 'Javelin Throw',    tagline: 'Power up. Release at the peak.',              href: '/games/javelin-throw',   accentColor: '#eab308', duration: '45s', icon: 'sports_track_and_field', category: 'sports', industries: ['sports', 'healthcare', 'technology'] },
  { id: 'bowling-curve',   title: 'Bowling Curve',    tagline: 'Hook it. Hit the pocket.',                    href: '/games/bowling-curve',   accentColor: '#7c3aed', duration: '45s', icon: 'sports_bowling',    category: 'sports', industries: ['sports', 'cpg', 'food_bev']         },
  { id: 'swimming-stroke', title: 'Swimming Stroke',  tagline: 'Alternate arms. Keep the pace.',              href: '/games/swimming-stroke', accentColor: '#0ea5e9', duration: '60s', icon: 'pool',              category: 'sports', industries: ['sports', 'healthcare', 'technology']  },
  { id: 'dart-board',      title: 'Dart Board',       tagline: 'Flick straight. Hit the bull.',               href: '/games/dart-board',      accentColor: '#dc2626', duration: '45s', icon: 'adjust',            category: 'sports', industries: ['sports', 'food_bev', 'retail']       },
  { id: 'track-sprint',    title: 'Track Sprint',     tagline: 'Alternate taps. Stay in your lane!',          href: '/games/track-sprint',    accentColor: '#f59e0b', duration: '30s', icon: 'directions_run',    category: 'sports', industries: ['sports', 'healthcare', 'retail']     },
  { id: 'discus-spin',     title: 'Discus Spin',      tagline: 'Spin it. Flick it. Fly!',                     href: '/games/discus-spin',     accentColor: '#10b981', duration: '45s', icon: 'rotate_right',      category: 'sports', industries: ['sports', 'cpg', 'technology']        },
  { id: 'boxing-combo',    title: 'Boxing Combo',     tagline: 'Jab. Cross. Hook. Repeat.',                   href: '/games/boxing-combo',    accentColor: '#ef4444', duration: '30s', icon: 'sports_mma',        category: 'sports', industries: ['sports', 'healthcare', 'cpg']        },
  { id: 'hoop-shot',      title: 'Hoop Shot',      tagline: 'Swipe to score. 60 seconds on the clock.',    href: '/games/hoop-shot',      accentColor: '#f97316', duration: '60s', icon: 'sports_basketball', category: 'sports', industries: ['sports', 'cpg', 'food_bev']           },
  { id: 'penalty-kick',   title: 'Penalty Kick',   tagline: 'Beat the keeper. Aim for the corners.',        href: '/games/penalty-kick',   accentColor: '#22c55e', duration: '60s', icon: 'sports_soccer',     category: 'sports', industries: ['sports', 'cpg', 'food_bev']           },
  { id: 'spiral-throw',   title: 'Spiral Throw',   tagline: "Lead your receiver. Don't throw behind.",      href: '/games/spiral-throw',   accentColor: '#f59e0b', duration: '60s', icon: 'sports_football',   category: 'sports', industries: ['sports', 'cpg', 'retail']             },
  { id: 'reflex-rally',   title: 'Reflex Rally',   tagline: "Return every shot. Don't miss.",               href: '/games/reflex-rally',   accentColor: '#84cc16', duration: '60s', icon: 'sports_tennis',     category: 'sports', industries: ['sports', 'technology', 'healthcare']  },
  { id: 'precision-putt', title: 'Precision Putt', tagline: 'Read the green. Control the power.',           href: '/games/precision-putt', accentColor: '#86efac', duration: '60s', icon: 'sports_golf',       category: 'sports', industries: ['sports', 'finance', 'retail']         },
];

export const HOLIDAY_GAMES: Game[] = [
  { id: 'gift-rush',        title: 'Gift Rush',        tagline: "Swipe left or right. Fast. Santa's watching.", href: '/games/gift-rush',        accentColor: '#ef4444', duration: '45s', icon: 'redeem',         category: 'holiday', industries: ['retail', 'cpg', 'food_bev']           },
  { id: 'snow-catch',       title: 'Snow Catch',       tagline: "Tilt to catch the snow. Miss one and it's over.", href: '/games/snow-catch',    accentColor: '#93c5fd', duration: '45s', icon: 'ac_unit',        category: 'holiday', industries: ['retail', 'cpg', 'food_bev']           },
  { id: 'boo-blast',        title: 'Boo Blast',        tagline: "Tap the ghosts. They won't wait.",              href: '/games/boo-blast',        accentColor: '#a855f7', duration: '30s', icon: 'ghost',          category: 'holiday', industries: ['cpg', 'food_bev', 'retail']           },
  { id: 'cauldron-bubble',  title: 'Cauldron Bubble',  tagline: 'Blow to bubble. Too quiet = dead. Too loud = BOOM.', href: '/games/cauldron-bubble', accentColor: '#22c55e', duration: '45s', icon: 'science',   category: 'holiday', industries: ['food_bev', 'cpg', 'retail']           },
  { id: 'firework-launch',  title: 'Firework Launch',  tagline: 'Swipe to launch. Tap to detonate. Make it count.', href: '/games/firework-launch', accentColor: '#f59e0b', duration: '45s', icon: 'celebration',  category: 'holiday', industries: ['sports', 'cpg', 'retail']             },
  { id: 'countdown-crush',  title: 'Countdown Crush',  tagline: 'Score before midnight. Every second counts.',   href: '/games/countdown-crush',  accentColor: '#fbbf24', duration: '30s', icon: 'timer',         category: 'holiday', industries: ['finance', 'technology', 'retail']     },
  { id: 'cupid-shot',       title: 'Cupid Shot',       tagline: 'Aim. Wait. Shoot at the perfect moment.',       href: '/games/cupid-shot',       accentColor: '#f43f5e', duration: '45s', icon: 'favorite',      category: 'holiday', industries: ['retail', 'cpg', 'food_bev']           },
  { id: 'love-note',        title: 'Love Note',        tagline: 'Remember the sequence. Tap it back. From the heart.', href: '/games/love-note', accentColor: '#ec4899', duration: '60s', icon: 'mail',           category: 'holiday', industries: ['retail', 'healthcare', 'cpg']         },
  { id: 'turkey-trot',      title: 'Turkey Trot',      tagline: "The turkey's running. Prove you're faster.",    href: '/games/turkey-trot',      accentColor: '#f97316', duration: '30s', icon: 'directions_run', category: 'holiday', industries: ['food_bev', 'cpg', 'retail']           },
  { id: 'harvest-catch',    title: 'Harvest Catch',    tagline: "Tilt to catch the harvest. Skip the Brussels sprouts.", href: '/games/harvest-catch', accentColor: '#d97706', duration: '45s', icon: 'agriculture', category: 'holiday', industries: ['food_bev', 'cpg', 'retail']           },
  { id: 'shamrock-shuffle', title: 'Shamrock Shuffle', tagline: 'Catch the luck. Dodge the coal.',                     href: '/games/shamrock-shuffle', accentColor: '#16a34a', duration: '30s', icon: 'eco',               category: 'holiday', industries: ['retail','food_bev','cpg']             },
  { id: 'egg-toss',         title: 'Egg Toss',         tagline: "Toss it. Catch it. Don't crack it!",                  href: '/games/egg-toss',        accentColor: '#fde68a', duration: '45s', icon: 'egg',               category: 'holiday', industries: ['food_bev','cpg','retail']             },
  { id: 'pinata-smash',     title: 'Piñata Smash',     tagline: 'Find the weak spot. Smash!',                          href: '/games/pinata-smash',    accentColor: '#ec4899', duration: '30s', icon: 'celebration',       category: 'holiday', industries: ['food_bev','cpg','retail']             },
  { id: 'flower-bouquet',   title: 'Flower Bouquet',   tagline: 'Catch the petals. Build love.',                       href: '/games/flower-bouquet',  accentColor: '#f472b6', duration: '45s', icon: 'local_florist',     category: 'holiday', industries: ['retail','cpg','healthcare']            },
  { id: 'bbq-master',       title: 'BBQ Master',       tagline: "Flip it right. Don't burn dad's burger.",             href: '/games/bbq-master',      accentColor: '#f97316', duration: '60s', icon: 'outdoor_grill',     category: 'holiday', industries: ['food_bev','cpg','retail']             },
  { id: 'sparkler-draw',    title: 'Sparkler Draw',    tagline: 'Draw with fire. Make it sparkle.',                    href: '/games/sparkler-draw',   accentColor: '#fbbf24', duration: '45s', icon: 'auto_awesome',      category: 'holiday', industries: ['retail','cpg','sports']               },
  { id: 'pencil-pack',      title: 'Pencil Pack',      tagline: 'Sort and pack. School starts now.',                   href: '/games/pencil-pack',     accentColor: '#3b82f6', duration: '30s', icon: 'school',            category: 'holiday', industries: ['retail','cpg','technology']            },
  { id: 'diya-light',       title: 'Diya Light',       tagline: 'Light the diyas. In order!',                          href: '/games/diya-light',      accentColor: '#f59e0b', duration: '45s', icon: 'emoji_objects',     category: 'holiday', industries: ['retail','cpg','food_bev']              },
  { id: 'dreidel-spin',     title: 'Dreidel Spin',     tagline: 'Flick it hard. Watch it spin!',                       href: '/games/dreidel-spin',    accentColor: '#3b82f6', duration: '30s', icon: 'rotate_right',      category: 'holiday', industries: ['retail','food_bev','cpg']              },
  { id: 'dragon-parade',    title: 'Dragon Parade',    tagline: 'Multi-touch the dragon. Make it dance!',              href: '/games/dragon-parade',   accentColor: '#ef4444', duration: '60s', icon: 'cruelty_free',      category: 'holiday', industries: ['retail','food_bev','cpg']              },
  { id: 'bead-catch',       title: 'Bead Catch',       tagline: 'Tilt to catch the beads!',                            href: '/games/bead-catch',      accentColor: '#a855f7', duration: '30s', icon: 'bubble_chart',      category: 'holiday', industries: ['retail','food_bev','cpg']              },
  { id: 'lantern-float',    title: 'Lantern Float',    tagline: 'Blow them up. Watch them rise.',                      href: '/games/lantern-float',   accentColor: '#f97316', duration: '45s', icon: 'light',             category: 'holiday', industries: ['retail','cpg','food_bev']              },
  { id: 'taco-toss',        title: 'Taco Toss',        tagline: 'Catch the fillings. Build the taco.',                 href: '/games/taco-toss',       accentColor: '#84cc16', duration: '45s', icon: 'lunch_dining',      category: 'holiday', industries: ['food_bev','cpg','retail']              },
  { id: 'basket-weave',     title: 'Basket Weave',     tagline: 'Over. Under. Don\'t drop a strand.',                  href: '/games/basket-weave',    accentColor: '#d97706', duration: '60s', icon: 'texture',           category: 'holiday', industries: ['retail','cpg','food_bev']              },
  { id: 'clover-path',      title: 'Clover Path',      tagline: 'Trace the lucky path. Don\'t stray!',                 href: '/games/clover-path',     accentColor: '#22c55e', duration: '45s', icon: 'route',             category: 'holiday', industries: ['retail','cpg','food_bev']              },
  { id: 'signal-boost',  title: 'Signal Boost',  tagline: 'Hum steady to keep the tower alive.',           href: '/games/signal-boost',  accentColor: '#f59e0b', duration: '45s', icon: 'cell_tower',          category: 'breath',    industries: ['technology', 'cpg', 'healthcare']  },
  { id: 'crystal-grow',  title: 'Crystal Grow',  tagline: 'Breathe steady to grow the crystal.',            href: '/games/crystal-grow',  accentColor: '#e879f9', duration: '45s', icon: 'diamond',             category: 'breath',    industries: ['healthcare', 'retail', 'technology'] },
];

export const BREATH_GAMES: Game[] = [
  { id: 'echo-clap',       title: 'Echo Clap',       tagline: 'Clap in time with the echo pattern. It speeds up!',       href: '/games/echo-clap',       accentColor: '#ef4444', duration: '45s', icon: 'music_note',          category: 'breath',    industries: ['cpg', 'food_bev', 'sports']              },
  { id: 'solar-charge',    title: 'Solar Charge',    tagline: 'Stay silent to charge the solar panel. Noise drains it!', href: '/games/solar-charge',    accentColor: '#facc15', duration: '45s', icon: 'sunny',               category: 'breath',    industries: ['technology', 'cpg', 'retail']            },
  { id: 'aurora-wave',     title: 'Aurora Wave',     tagline: 'Breathe slowly to paint aurora waves. Erratic = broken!', href: '/games/aurora-wave',     accentColor: '#34d399', duration: '60s', icon: 'nights_stay',         category: 'breath',    industries: ['healthcare', 'technology', 'retail']     },
  { id: 'dragon-breath',   title: 'Dragon Breath',    tagline: 'Blow hard. Breathe fire!',                          href: '/games/dragon-breath',   accentColor: '#ef4444', duration: '30s', icon: 'local_fire_department', category: 'breath', industries: ['cpg','food_bev','sports']            },
  { id: 'voice-sculpt',    title: 'Voice Sculpt',     tagline: 'Hum to shape the clay.',                            href: '/games/voice-sculpt',    accentColor: '#d946ef', duration: '45s', icon: 'record_voice_over',   category: 'breath', industries: ['healthcare','retail','technology']    },
  { id: 'echo-match',      title: 'Echo Match',       tagline: 'Match the echo. Hold the note.',                    href: '/games/echo-match',      accentColor: '#06b6d4', duration: '45s', icon: 'graphic_eq',          category: 'breath', industries: ['healthcare','cpg','retail']           },
  { id: 'howl-wolf',       title: 'Howl Wolf',        tagline: 'Find your pitch. Call the pack.',                   href: '/games/howl-wolf',       accentColor: '#6366f1', duration: '45s', icon: 'pets',                category: 'breath', industries: ['cpg','retail','food_bev']             },
  { id: 'beat-box',        title: 'Beat Box',         tagline: 'Drop the beat. Keep it going.',                     href: '/games/beat-box',        accentColor: '#f97316', duration: '60s', icon: 'music_note',          category: 'breath', industries: ['cpg','food_bev','retail']             },
  { id: 'hum-maze',        title: 'Hum Maze',         tagline: 'Change your pitch. Navigate.',                      href: '/games/hum-maze',        accentColor: '#14b8a6', duration: '60s', icon: 'route',               category: 'breath', industries: ['healthcare','technology','retail']    },
  { id: 'chant-power',     title: 'Chant Power',      tagline: 'Hold the chant. Charge the power.',                 href: '/games/chant-power',     accentColor: '#dc2626', duration: '45s', icon: 'record_voice_over',   category: 'breath', industries: ['sports','cpg','food_bev']             },
  { id: 'whistle-launch',  title: 'Whistle Launch',   tagline: 'Whistle to launch. Pitch to steer.',                href: '/games/whistle-launch',  accentColor: '#fbbf24', duration: '45s', icon: 'rocket',              category: 'breath', industries: ['technology','cpg','sports']            },
  { id: 'vocal-shield',    title: 'Vocal Shield',     tagline: 'Sing it. Block it. Hold it.',                       href: '/games/vocal-shield',    accentColor: '#818cf8', duration: '30s', icon: 'shield',              category: 'breath', industries: ['healthcare','technology','sports']    },
  { id: 'breath-sculpt',   title: 'Breath Sculpt',    tagline: 'Breathe to shape. Slow or fast.',                   href: '/games/breath-sculpt',   accentColor: '#34d399', duration: '60s', icon: 'air',                 category: 'breath', industries: ['healthcare','cpg','retail']           },
  { id: 'frequency-tune',  title: 'Frequency Tune',   tagline: 'Find the frequency. Hold it.',                      href: '/games/frequency-tune',  accentColor: '#f472b6', duration: '45s', icon: 'tune',                category: 'breath', industries: ['technology','healthcare','automotive'] },
  { id: 'lung-capacity',   title: 'Lung Capacity',    tagline: 'Take one breath. Hold the note.',                   href: '/games/lung-capacity',   accentColor: '#4ade80', duration: '30s', icon: 'pulmonology',         category: 'breath', industries: ['healthcare','sports','cpg']            },
  { id: 'sound-waves',     title: 'Sound Waves',      tagline: 'Shout the frequency. Shatter walls.',               href: '/games/sound-waves',     accentColor: '#22d3ee', duration: '45s', icon: 'graphic_eq',          category: 'breath', industries: ['technology','cpg','sports']            },
  { id: 'sing-along',      title: 'Sing Along',       tagline: 'Match the note. Hold it perfect.',                  href: '/games/sing-along',      accentColor: '#fb7185', duration: '45s', icon: 'mic',                 category: 'breath', industries: ['cpg','retail','food_bev']              },
  { id: 'morse-tap',       title: 'Morse Tap',        tagline: 'Tap the code. Send the message.',                   href: '/games/morse-tap',       accentColor: '#fbbf24', duration: '45s', icon: 'radio',               category: 'breath', industries: ['technology','automotive','finance']    },
  { id: 'morse-decode',  title: 'Morse Decode',  tagline: 'Flash by flash — what is the letter?',          href: '/games/morse-decode',  accentColor: '#facc15', duration: '60s', icon: 'radio',               category: 'cognitive', industries: ['technology', 'finance', 'healthcare'] },
  { id: 'code-breaker',  title: 'Code Breaker',  tagline: 'Memorize. Hide. Enter. Beat the clock.',         href: '/games/code-breaker',  accentColor: '#06b6d4', duration: '60s', icon: 'lock',                category: 'cognitive', industries: ['technology', 'finance', 'retail']   },
];

export const EXTRA_COGNITIVE_GAMES: Game[] = [
  { id: 'pulse-jump',      title: 'Pulse Jump',      tagline: 'Tap in rhythm with the beat. Miss the pulse — fall!',     href: '/games/pulse-jump',      accentColor: '#a855f7', duration: '60s', icon: 'music_note',          category: 'cognitive', industries: ['sports', 'cpg', 'technology']            },
  { id: 'domino-chain',    title: 'Domino Chain',    tagline: 'Tap the first domino at the perfect moment. Chain falls!', href: '/games/domino-chain',    accentColor: '#f97316', duration: '60s', icon: 'view_column',         category: 'cognitive', industries: ['technology', 'finance', 'retail']        },
  { id: 'number-crunch',   title: 'Number Crunch',   tagline: 'Solve the math problem. Tap the right answer — fast!',    href: '/games/number-crunch',   accentColor: '#3b82f6', duration: '60s', icon: 'calculate',           category: 'cognitive', industries: ['finance', 'technology', 'healthcare']    },
  { id: 'mirror-mind',     title: 'Mirror Mind',      tagline: 'Both hands. Mirrored. Synchronized.',               href: '/games/mirror-mind',     accentColor: '#8b5cf6', duration: '45s', icon: 'flip',                category: 'cognitive', industries: ['technology','healthcare','finance']   },
  { id: 'number-path',     title: 'Number Path',      tagline: '1 to N. Fastest finger wins.',                      href: '/games/number-path',     accentColor: '#22c55e', duration: '45s', icon: '123',                 category: 'cognitive', industries: ['finance','technology','healthcare']   },
  { id: 'logic-gate',      title: 'Logic Gate',       tagline: 'Wire the circuit. Get the output.',                  href: '/games/logic-gate',      accentColor: '#64748b', duration: '60s', icon: 'device_hub',          category: 'cognitive', industries: ['technology','finance','automotive']   },
  { id: 'binary-decode',   title: 'Binary Decode',    tagline: 'Flip the bits. Find the number.',                   href: '/games/binary-decode',   accentColor: '#22c55e', duration: '45s', icon: 'data_object',         category: 'cognitive', industries: ['technology','finance','automotive']   },
  { id: 'attention-switch',title: 'Attention Switch', tagline: 'Dual task. Both streams. Now!',                     href: '/games/attention-switch',accentColor: '#6366f1', duration: '45s', icon: 'switch_access_shortcut',category:'cognitive',industries:['technology','finance','healthcare']    },
  { id: 'face-memory',     title: 'Face Memory',      tagline: 'Remember the faces. Spot them.',                    href: '/games/face-memory',     accentColor: '#f43f5e', duration: '60s', icon: 'face',                category: 'cognitive', industries: ['retail','healthcare','finance']       },
  { id: 'inference-trail', title: 'Inference Trail',  tagline: 'Follow the clues. Find the answer.',                href: '/games/inference-trail', accentColor: '#7c3aed', duration: '60s', icon: 'lightbulb',           category: 'cognitive', industries: ['finance','technology','healthcare']   },
  { id: 'spatial-map',     title: 'Spatial Map',      tagline: 'Study the map. Answer fast.',                       href: '/games/spatial-map',     accentColor: '#0ea5e9', duration: '60s', icon: 'map',                 category: 'cognitive', industries: ['automotive','technology','retail']    },
  { id: 'neon-chess',      title: 'Neon Chess',       tagline: 'One move. Best move. Neon style.',                  href: '/games/neon-chess',      accentColor: '#00ffff', duration: '60s', icon: 'grid_view',           category: 'cognitive', industries: ['technology','finance','healthcare']   },
  { id: 'shape-rotate',    title: 'Shape Rotate',     tagline: 'Spin it in your mind. Match it.',                   href: '/games/shape-rotate',    accentColor: '#06b6d4', duration: '60s', icon: '3d_rotation',         category: 'cognitive', industries: ['technology','automotive','finance']   },
  { id: 'type-speed',      title: 'Type Speed',       tagline: 'Type it fast. Beat the buzzer.',                    href: '/games/type-speed',      accentColor: '#e879f9', duration: '30s', icon: 'keyboard',            category: 'cognitive', industries: ['technology','finance','healthcare']   },
];

export const EXTRA_SKILL_GAMES: Game[] = [
  { id: 'bubble-burst',    title: 'Bubble Burst',     tagline: 'Pinch at the perfect size!',                        href: '/games/bubble-burst',    accentColor: '#67e8f9', duration: '30s', icon: 'bubble_chart',        category: 'skill',   industries: ['cpg','retail','food_bev']              },
  { id: 'tower-stack',     title: 'Tower Stack',      tagline: "Drop it. Stack it. Don't tip it.",                  href: '/games/tower-stack',     accentColor: '#f59e0b', duration: '60s', icon: 'view_in_ar',          category: 'skill',   industries: ['cpg','retail','food_bev']              },
  { id: 'bounce-pass',     title: 'Bounce Pass',      tagline: 'Angle the bounce. Make the pass.',                  href: '/games/bounce-pass',     accentColor: '#84cc16', duration: '45s', icon: 'sports',              category: 'skill',   industries: ['sports','technology','cpg']            },
  { id: 'gear-grind',      title: 'Gear Grind',       tagline: 'Mesh the gears. Keep it spinning.',                 href: '/games/gear-grind',      accentColor: '#94a3b8', duration: '60s', icon: 'settings',            category: 'skill',   industries: ['automotive','technology','finance']    },
  { id: 'thread-needle',   title: 'Thread Needle',    tagline: 'Steady hands only. Pros need not apply.',           href: '/games/thread-needle',   accentColor: '#e879f9', duration: '30s', icon: 'pivot_table_chart',   category: 'skill',   industries: ['healthcare','retail','cpg']            },
  { id: 'jigsaw-rush',     title: 'Jigsaw Rush',      tagline: "Snap it. Fast. Clock's ticking.",                   href: '/games/jigsaw-rush',     accentColor: '#fbbf24', duration: '60s', icon: 'extension',           category: 'skill',   industries: ['retail','technology','cpg']            },
  { id: 'cable-wrap',      title: 'Cable Wrap',       tagline: 'No tangles. No mercy.',                             href: '/games/cable-wrap',      accentColor: '#34d399', duration: '45s', icon: 'cable',               category: 'skill',   industries: ['technology','automotive','retail']     },
  { id: 'magnet-maze',     title: 'Magnet Maze',      tagline: 'Attract, repel, navigate.',                         href: '/games/magnet-maze',     accentColor: '#ef4444', duration: '60s', icon: 'explore',             category: 'skill',   industries: ['technology','automotive','healthcare'] },
  { id: 'cosmic-catch',    title: 'Cosmic Catch',     tagline: 'Swipe the stars before they fade.',                 href: '/games/cosmic-catch',    accentColor: '#6366f1', duration: '30s', icon: 'stars',               category: 'skill',   industries: ['technology','cpg','retail']            },
  { id: 'wormhole-dive',   title: 'Wormhole Dive',    tagline: 'Survive the warp. Keep diving.',                    href: '/games/wormhole-dive',   accentColor: '#7c3aed', duration: '60s', icon: 'blur_circular',       category: 'skill',   industries: ['technology','automotive','finance']    },
  { id: 'dream-catch',     title: 'Dream Catch',      tagline: 'Float through. Catch the fragments.',               href: '/games/dream-catch',     accentColor: '#818cf8', duration: '60s', icon: 'nights_stay',         category: 'skill',   industries: ['healthcare','retail','technology']     },
  { id: 'sound-garden',    title: 'Sound Garden',     tagline: 'Touch to grow. Grow to play.',                      href: '/games/sound-garden',    accentColor: '#4ade80', duration: '60s', icon: 'nature',              category: 'skill',   industries: ['healthcare','retail','technology']     },
];

export const EXTRA_SPORTS_GAMES: Game[] = [
  { id: 'curling-sweep',   title: 'Curling Sweep',    tagline: 'Sweep it in. Sweep it hard.',                       href: '/games/curling-sweep',   accentColor: '#67e8f9', duration: '60s', icon: 'cleaning_services',   category: 'sports', industries: ['sports','cpg','retail']               },
  { id: 'rowing-rhythm',   title: 'Rowing Rhythm',    tagline: 'Sync your strokes. Row!',                           href: '/games/rowing-rhythm',   accentColor: '#38bdf8', duration: '60s', icon: 'rowing',              category: 'sports', industries: ['sports','healthcare','food_bev']      },
  { id: 'baseball-swing',  title: 'Baseball Swing',   tagline: 'Watch the pitch. Swing!',                           href: '/games/baseball-swing',  accentColor: '#fbbf24', duration: '45s', icon: 'sports_baseball',     category: 'sports', industries: ['sports','cpg','food_bev']              },
  { id: 'karate-chop',     title: 'Karate Chop',      tagline: 'Chop the right zone. Kata master.',                 href: '/games/karate-chop',     accentColor: '#ef4444', duration: '30s', icon: 'sports_martial_arts', category: 'sports', industries: ['sports','healthcare','technology']    },
  { id: 'pole-vault',      title: 'Pole Vault',       tagline: 'Run. Plant. Fly. Clear it!',                        href: '/games/pole-vault',      accentColor: '#a3e635', duration: '45s', icon: 'sports_gymnastics',   category: 'sports', industries: ['sports','healthcare','cpg']            },
  { id: 'table-tennis',    title: 'Table Tennis',     tagline: "Return everything. Don't blink.",                   href: '/games/table-tennis',    accentColor: '#fb923c', duration: '45s', icon: 'sports_tennis',       category: 'sports', industries: ['sports','technology','cpg']            },
  { id: 'gymnast-beam',    title: 'Gymnast Beam',     tagline: 'Balance. Execute. Stick the landing.',              href: '/games/gymnast-beam',    accentColor: '#f472b6', duration: '60s', icon: 'accessibility',       category: 'sports', industries: ['sports','healthcare','retail']        },
  { id: 'pixel-skate',     title: 'Pixel Skate',      tagline: 'Flick tricks. Stack the combo.',                    href: '/games/pixel-skate',     accentColor: '#10b981', duration: '45s', icon: 'skateboarding',       category: 'sports', industries: ['sports','retail','technology']        },
  { id: 'surf-ride',       title: 'Surf Ride',        tagline: 'Tilt to balance. Swipe for tricks.',                href: '/games/surf-ride',       accentColor: '#06b6d4', duration: '60s', icon: 'surfing',             category: 'sports', industries: ['sports','cpg','retail']               },
  { id: 'ski-slalom',      title: 'Ski Slalom',       tagline: 'Weave through the gates. Go fast.',                 href: '/games/ski-slalom',      accentColor: '#818cf8', duration: '45s', icon: 'downhill_skiing',     category: 'sports', industries: ['sports','cpg','automotive']            },
];

export const NEW_GAMES: Game[] = [
  { id: 'mirror-dance', title: 'Mirror Dance',  tagline: 'Match the mirror. Move with the beat.',       href: '/games/mirror-dance', accentColor: '#ec4899', duration: '60s', icon: 'person',          category: 'cognitive', industries: ['cpg', 'retail', 'technology']         },
  { id: 'sand-pour',    title: 'Sand Pour',     tagline: "Fill the glass. Don't spill.",                href: '/games/sand-pour',    accentColor: '#f59e0b', duration: '60s', icon: 'hourglass_empty', category: 'skill',     industries: ['food_bev', 'cpg', 'retail']           },
  { id: 'color-blend',  title: 'Color Blend',   tagline: 'Swipe to blend. Hit the target hue.',         href: '/games/color-blend',  accentColor: '#a855f7', duration: '60s', icon: 'palette',         category: 'cognitive', industries: ['cpg', 'retail', 'technology']         },
  { id: 'echo-tap',     title: 'Echo Tap',      tagline: 'Listen. Repeat the pattern.',                 href: '/games/echo-tap',     accentColor: '#06b6d4', duration: '60s', icon: 'volume_up',       category: 'cognitive', industries: ['technology', 'retail', 'cpg']         },
  { id: 'heat-map',     title: 'Heat Map',      tagline: 'Where do you look first?',                    href: '/games/heat-map',     accentColor: '#f97316', duration: '60s', icon: 'visibility',      category: 'cognitive', industries: ['retail', 'cpg', 'technology']         },
  { id: 'trust-fall',   title: 'Trust Fall',    tagline: 'Let go at the right moment.',                 href: '/games/trust-fall',   accentColor: '#8b5cf6', duration: '60s', icon: 'arrow_downward',  category: 'cognitive', industries: ['healthcare', 'technology', 'retail']  },
  { id: 'spark-chain',  title: 'Spark Chain',   tagline: 'One spark. Maximum spread.',                  href: '/games/spark-chain',  accentColor: '#f97316', duration: '60s', icon: 'bolt',            category: 'skill',     industries: ['technology', 'cpg', 'retail']         },
  { id: 'crowd-pulse',  title: 'Crowd Pulse',   tagline: 'Feel the room.',                              href: '/games/crowd-pulse',  accentColor: '#a855f7', duration: '60s', icon: 'graphic_eq',      category: 'skill',     industries: ['cpg', 'retail', 'food_bev']           },
];

import { GAME_MEASURES } from './measures';

const _ALL: Game[] = [...SKILL_GAMES, ...SPORTS_GAMES, ...HOLIDAY_GAMES, ...BREATH_GAMES, ...EXTRA_COGNITIVE_GAMES, ...EXTRA_SKILL_GAMES, ...EXTRA_SPORTS_GAMES, ...NEW_GAMES];
export const ALL_GAMES: Game[] = _ALL.map(g => ({ ...g, measures: GAME_MEASURES[g.id] ?? [] }));

export const FEATURED_GAMES: Game[] = [
  SKILL_GAMES[0],
  SKILL_GAMES[1],
  SKILL_GAMES[4],
  SKILL_GAMES[9],
  HOLIDAY_GAMES[2],
  HOLIDAY_GAMES[4],
];

const NEW_ARRIVAL_IDS = ['harvest-catch', 'love-note', 'countdown-crush', 'cauldron-bubble', 'snow-catch'];
export const NEW_ARRIVALS: Game[] = NEW_ARRIVAL_IDS
  .map(id => ALL_GAMES.find(g => g.id === id))
  .filter((g): g is Game => g !== undefined);

// ─── Category config ──────────────────────────────────────────────────────────

export const CATEGORY_META: Record<GameCategory, { label: string }> = {
  skill:     { label: 'SKILL'   },
  sports:    { label: 'SPORTS'  },
  holiday:   { label: 'HOLIDAY' },
  cognitive: { label: 'BRAIN'   },
  breath:    { label: 'BREATH'  },
};

// ─── Industry config ──────────────────────────────────────────────────────────

export const INDUSTRIES: { id: Industry; label: string; icon: string }[] = [
  { id: 'cpg',        label: 'CPG',        icon: '🏪' },
  { id: 'food_bev',   label: 'Food & Bev', icon: '🍺' },
  { id: 'sports',     label: 'Sports',     icon: '🏆' },
  { id: 'technology', label: 'Technology', icon: '💻' },
  { id: 'healthcare', label: 'Healthcare', icon: '❤️' },
  { id: 'finance',    label: 'Finance',    icon: '📊' },
  { id: 'retail',     label: 'Retail',     icon: '🛍️' },
  { id: 'automotive', label: 'Automotive', icon: '🚗' },
];
